// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::needless_borrow
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.11.1";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = 1933904176;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__analysis__quality__calculate_jitter_stats_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "calculate_jitter_stats",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_latencies = <Vec<u64>>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok(
                        crate::api::analysis::quality::calculate_jitter_stats(&api_latencies),
                    )?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__probes__captive_portal__check_for_captive_portal_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "check_for_captive_portal",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_timeout_ms = <u64>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, ()>(
                    (move || async move {
                        let output_ok = Result::<_, ()>::Ok(
                            crate::api::probes::captive_portal::check_for_captive_portal(
                                api_timeout_ms,
                            )
                            .await,
                        )?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__engine__check_network_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "check_network",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_config =
                <crate::api::models::config::NetworkConfiguration>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, ()>(
                    (move || async move {
                        let output_ok = Result::<_, ()>::Ok(
                            crate::api::engine::check_network(api_config).await,
                        )?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__probes__target__check_target_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "check_target",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_target =
                <crate::api::models::target::NetworkTarget>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, ()>(
                    (move || async move {
                        let output_ok = Result::<_, ()>::Ok(
                            crate::api::probes::target::check_target(&api_target).await,
                        )?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__probes__dns__detect_dns_hijacking_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "detect_dns_hijacking",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_domain = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, ()>(
                    (move || async move {
                        let output_ok = Result::<_, ()>::Ok(
                            crate::api::probes::dns::detect_dns_hijacking(&api_domain).await,
                        )?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__probes__interface__detect_security_and_network_type_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "detect_security_and_network_type",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok(
                        crate::api::probes::interface::detect_security_and_network_type(),
                    )?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__analysis__quality__evaluate_quality_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "evaluate_quality",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_latency = <u64>::sse_decode(&mut deserializer);
            let api_threshold =
                <crate::api::models::config::QualityThresholds>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok =
                        Result::<_, ()>::Ok(crate::api::analysis::quality::evaluate_quality(
                            api_latency,
                            &api_threshold,
                        ))?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__models__config__network_configuration_default_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "network_configuration_default",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok(
                        crate::api::models::config::NetworkConfiguration::default(),
                    )?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__models__config__quality_thresholds_default_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "quality_thresholds_default",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok(
                        crate::api::models::config::QualityThresholds::default(),
                    )?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__models__config__resilience_config_default_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "resilience_config_default",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok(
                        crate::api::models::config::ResilienceConfig::default(),
                    )?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__models__config__security_config_default_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "security_config_default",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok =
                        Result::<_, ()>::Ok(crate::api::models::config::SecurityConfig::default())?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__models__net_info__security_flags_default_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "security_flags_default",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok(
                        crate::api::models::net_info::SecurityFlags::default(),
                    )?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__probes__traceroute__trace_route_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "trace_route",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_host = <String>::sse_decode(&mut deserializer);
            let api_max_hops = <u8>::sse_decode(&mut deserializer);
            let api_timeout_per_hop_ms = <u64>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, ()>(
                    (move || async move {
                        let output_ok = Result::<_, ()>::Ok(
                            crate::api::probes::traceroute::trace_route(
                                api_host,
                                api_max_hops,
                                api_timeout_per_hop_ms,
                            )
                            .await,
                        )?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}

// Section: dart2rust

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for crate::api::models::net_info::CaptivePortalStatus {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_isCaptivePortal = <bool>::sse_decode(deserializer);
        let mut var_redirectUrl = <Option<String>>::sse_decode(deserializer);
        return crate::api::models::net_info::CaptivePortalStatus {
            is_captive_portal: var_isCaptivePortal,
            redirect_url: var_redirectUrl,
        };
    }
}

impl SseDecode for crate::api::models::config::CheckStrategy {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::models::config::CheckStrategy::Race,
            1 => crate::api::models::config::CheckStrategy::Consensus,
            _ => unreachable!("Invalid variant for CheckStrategy: {}", inner),
        };
    }
}

impl SseDecode for crate::api::models::config::ConnectionQuality {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::models::config::ConnectionQuality::Excellent,
            1 => crate::api::models::config::ConnectionQuality::Great,
            2 => crate::api::models::config::ConnectionQuality::Good,
            3 => crate::api::models::config::ConnectionQuality::Moderate,
            4 => crate::api::models::config::ConnectionQuality::Poor,
            5 => crate::api::models::config::ConnectionQuality::Unstable,
            6 => crate::api::models::config::ConnectionQuality::Offline,
            _ => unreachable!("Invalid variant for ConnectionQuality: {}", inner),
        };
    }
}

impl SseDecode for crate::api::models::net_info::ConnectionType {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::models::net_info::ConnectionType::Wifi,
            1 => crate::api::models::net_info::ConnectionType::Cellular,
            2 => crate::api::models::net_info::ConnectionType::Ethernet,
            3 => crate::api::models::net_info::ConnectionType::Vpn,
            4 => crate::api::models::net_info::ConnectionType::Bluetooth,
            5 => crate::api::models::net_info::ConnectionType::Unknown,
            _ => unreachable!("Invalid variant for ConnectionType: {}", inner),
        };
    }
}

impl SseDecode for f32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_f32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for f64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_f64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for crate::api::models::report::LatencyStats {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_latencyMs = <u64>::sse_decode(deserializer);
        let mut var_jitterMs = <u64>::sse_decode(deserializer);
        let mut var_packetLossPercent = <f32>::sse_decode(deserializer);
        let mut var_minLatencyMs = <Option<u64>>::sse_decode(deserializer);
        let mut var_avgLatencyMs = <Option<u64>>::sse_decode(deserializer);
        let mut var_maxLatencyMs = <Option<u64>>::sse_decode(deserializer);
        let mut var_stabilityScore = <u8>::sse_decode(deserializer);
        return crate::api::models::report::LatencyStats {
            latency_ms: var_latencyMs,
            jitter_ms: var_jitterMs,
            packet_loss_percent: var_packetLossPercent,
            min_latency_ms: var_minLatencyMs,
            avg_latency_ms: var_avgLatencyMs,
            max_latency_ms: var_maxLatencyMs,
            stability_score: var_stabilityScore,
        };
    }
}

impl SseDecode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<String>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::models::target::NetworkTarget> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<crate::api::models::target::NetworkTarget>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<u64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<u64>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::models::report::TargetReport> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<crate::api::models::report::TargetReport>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::models::net_info::TraceHop> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<crate::api::models::net_info::TraceHop>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for crate::api::models::config::NetworkConfiguration {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_targets =
            <Vec<crate::api::models::target::NetworkTarget>>::sse_decode(deserializer);
        let mut var_checkIntervalMs = <u64>::sse_decode(deserializer);
        let mut var_qualityThreshold =
            <crate::api::models::config::QualityThresholds>::sse_decode(deserializer);
        let mut var_security =
            <crate::api::models::config::SecurityConfig>::sse_decode(deserializer);
        let mut var_resilience =
            <crate::api::models::config::ResilienceConfig>::sse_decode(deserializer);
        return crate::api::models::config::NetworkConfiguration {
            targets: var_targets,
            check_interval_ms: var_checkIntervalMs,
            quality_threshold: var_qualityThreshold,
            security: var_security,
            resilience: var_resilience,
        };
    }
}

impl SseDecode for crate::api::models::report::NetworkReport {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_timestampMs = <u64>::sse_decode(deserializer);
        let mut var_status = <crate::api::models::report::NetworkStatus>::sse_decode(deserializer);
        let mut var_connectionType =
            <crate::api::models::net_info::ConnectionType>::sse_decode(deserializer);
        let mut var_securityFlags =
            <crate::api::models::net_info::SecurityFlags>::sse_decode(deserializer);
        let mut var_targetReports =
            <Vec<crate::api::models::report::TargetReport>>::sse_decode(deserializer);
        return crate::api::models::report::NetworkReport {
            timestamp_ms: var_timestampMs,
            status: var_status,
            connection_type: var_connectionType,
            security_flags: var_securityFlags,
            target_reports: var_targetReports,
        };
    }
}

impl SseDecode for crate::api::models::report::NetworkStatus {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_isConnected = <bool>::sse_decode(deserializer);
        let mut var_quality =
            <crate::api::models::config::ConnectionQuality>::sse_decode(deserializer);
        let mut var_latencyStats =
            <crate::api::models::report::LatencyStats>::sse_decode(deserializer);
        let mut var_winnerTarget = <String>::sse_decode(deserializer);
        return crate::api::models::report::NetworkStatus {
            is_connected: var_isConnected,
            quality: var_quality,
            latency_stats: var_latencyStats,
            winner_target: var_winnerTarget,
        };
    }
}

impl SseDecode for crate::api::models::target::NetworkTarget {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_label = <String>::sse_decode(deserializer);
        let mut var_host = <String>::sse_decode(deserializer);
        let mut var_port = <u16>::sse_decode(deserializer);
        let mut var_protocol =
            <crate::api::models::target::TargetProtocol>::sse_decode(deserializer);
        let mut var_timeoutMs = <u64>::sse_decode(deserializer);
        let mut var_priority = <u8>::sse_decode(deserializer);
        let mut var_isEssential = <bool>::sse_decode(deserializer);
        return crate::api::models::target::NetworkTarget {
            label: var_label,
            host: var_host,
            port: var_port,
            protocol: var_protocol,
            timeout_ms: var_timeoutMs,
            priority: var_priority,
            is_essential: var_isEssential,
        };
    }
}

impl SseDecode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<String>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<f64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<f64>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<u64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<u64>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for crate::api::models::config::QualityThresholds {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_excellent = <u64>::sse_decode(deserializer);
        let mut var_great = <u64>::sse_decode(deserializer);
        let mut var_good = <u64>::sse_decode(deserializer);
        let mut var_moderate = <u64>::sse_decode(deserializer);
        let mut var_poor = <u64>::sse_decode(deserializer);
        return crate::api::models::config::QualityThresholds {
            excellent: var_excellent,
            great: var_great,
            good: var_good,
            moderate: var_moderate,
            poor: var_poor,
        };
    }
}

impl SseDecode for (Option<u64>, Option<u64>, Option<u64>, Option<f64>) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_field0 = <Option<u64>>::sse_decode(deserializer);
        let mut var_field1 = <Option<u64>>::sse_decode(deserializer);
        let mut var_field2 = <Option<u64>>::sse_decode(deserializer);
        let mut var_field3 = <Option<f64>>::sse_decode(deserializer);
        return (var_field0, var_field1, var_field2, var_field3);
    }
}

impl SseDecode
    for (
        crate::api::models::net_info::SecurityFlags,
        crate::api::models::net_info::ConnectionType,
    )
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_field0 =
            <crate::api::models::net_info::SecurityFlags>::sse_decode(deserializer);
        let mut var_field1 =
            <crate::api::models::net_info::ConnectionType>::sse_decode(deserializer);
        return (var_field0, var_field1);
    }
}

impl SseDecode for crate::api::models::config::ResilienceConfig {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_strategy =
            <crate::api::models::config::CheckStrategy>::sse_decode(deserializer);
        let mut var_circuitBreakerThreshold = <u8>::sse_decode(deserializer);
        let mut var_numJitterSamples = <u8>::sse_decode(deserializer);
        let mut var_jitterThresholdPercent = <f64>::sse_decode(deserializer);
        let mut var_stabilityThershold = <u8>::sse_decode(deserializer);
        let mut var_criticalPacketLossPrecent = <f32>::sse_decode(deserializer);
        return crate::api::models::config::ResilienceConfig {
            strategy: var_strategy,
            circuit_breaker_threshold: var_circuitBreakerThreshold,
            num_jitter_samples: var_numJitterSamples,
            jitter_threshold_percent: var_jitterThresholdPercent,
            stability_thershold: var_stabilityThershold,
            critical_packet_loss_precent: var_criticalPacketLossPrecent,
        };
    }
}

impl SseDecode for crate::api::models::config::SecurityConfig {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_blockVpn = <bool>::sse_decode(deserializer);
        let mut var_detectDnsHijack = <bool>::sse_decode(deserializer);
        let mut var_allowedInterfaces = <Vec<String>>::sse_decode(deserializer);
        return crate::api::models::config::SecurityConfig {
            block_vpn: var_blockVpn,
            detect_dns_hijack: var_detectDnsHijack,
            allowed_interfaces: var_allowedInterfaces,
        };
    }
}

impl SseDecode for crate::api::models::net_info::SecurityFlags {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_isVpnDetected = <bool>::sse_decode(deserializer);
        let mut var_isDnsSpoofed = <bool>::sse_decode(deserializer);
        let mut var_isProxyDetected = <bool>::sse_decode(deserializer);
        let mut var_interfaceName = <String>::sse_decode(deserializer);
        return crate::api::models::net_info::SecurityFlags {
            is_vpn_detected: var_isVpnDetected,
            is_dns_spoofed: var_isDnsSpoofed,
            is_proxy_detected: var_isProxyDetected,
            interface_name: var_interfaceName,
        };
    }
}

impl SseDecode for crate::api::models::target::TargetProtocol {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::models::target::TargetProtocol::Tcp,
            1 => crate::api::models::target::TargetProtocol::Udp,
            _ => unreachable!("Invalid variant for TargetProtocol: {}", inner),
        };
    }
}

impl SseDecode for crate::api::models::report::TargetReport {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_label = <String>::sse_decode(deserializer);
        let mut var_success = <bool>::sse_decode(deserializer);
        let mut var_latencyMs = <u64>::sse_decode(deserializer);
        let mut var_error = <Option<String>>::sse_decode(deserializer);
        let mut var_isEssential = <bool>::sse_decode(deserializer);
        return crate::api::models::report::TargetReport {
            label: var_label,
            success: var_success,
            latency_ms: var_latencyMs,
            error: var_error,
            is_essential: var_isEssential,
        };
    }
}

impl SseDecode for crate::api::models::net_info::TraceHop {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_hopNumber = <u8>::sse_decode(deserializer);
        let mut var_ipAddress = <String>::sse_decode(deserializer);
        let mut var_hostname = <Option<String>>::sse_decode(deserializer);
        let mut var_latencyMs = <Option<u64>>::sse_decode(deserializer);
        return crate::api::models::net_info::TraceHop {
            hop_number: var_hopNumber,
            ip_address: var_ipAddress,
            hostname: var_hostname,
            latency_ms: var_latencyMs,
        };
    }
}

impl SseDecode for u16 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u16::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => wire__crate__api__analysis__quality__calculate_jitter_stats_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        2 => wire__crate__api__probes__captive_portal__check_for_captive_portal_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        3 => wire__crate__api__engine__check_network_impl(port, ptr, rust_vec_len, data_len),
        4 => wire__crate__api__probes__target__check_target_impl(port, ptr, rust_vec_len, data_len),
        5 => wire__crate__api__probes__dns__detect_dns_hijacking_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        6 => wire__crate__api__probes__interface__detect_security_and_network_type_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        7 => wire__crate__api__analysis__quality__evaluate_quality_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        8 => wire__crate__api__models__config__network_configuration_default_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        9 => wire__crate__api__models__config__quality_thresholds_default_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        10 => wire__crate__api__models__config__resilience_config_default_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        11 => wire__crate__api__models__config__security_config_default_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        12 => wire__crate__api__models__net_info__security_flags_default_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        13 => wire__crate__api__probes__traceroute__trace_route_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::models::net_info::CaptivePortalStatus {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.is_captive_portal.into_into_dart().into_dart(),
            self.redirect_url.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::models::net_info::CaptivePortalStatus
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::models::net_info::CaptivePortalStatus>
    for crate::api::models::net_info::CaptivePortalStatus
{
    fn into_into_dart(self) -> crate::api::models::net_info::CaptivePortalStatus {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::models::config::CheckStrategy {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Race => 0.into_dart(),
            Self::Consensus => 1.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::models::config::CheckStrategy
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::models::config::CheckStrategy>
    for crate::api::models::config::CheckStrategy
{
    fn into_into_dart(self) -> crate::api::models::config::CheckStrategy {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::models::config::ConnectionQuality {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Excellent => 0.into_dart(),
            Self::Great => 1.into_dart(),
            Self::Good => 2.into_dart(),
            Self::Moderate => 3.into_dart(),
            Self::Poor => 4.into_dart(),
            Self::Unstable => 5.into_dart(),
            Self::Offline => 6.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::models::config::ConnectionQuality
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::models::config::ConnectionQuality>
    for crate::api::models::config::ConnectionQuality
{
    fn into_into_dart(self) -> crate::api::models::config::ConnectionQuality {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::models::net_info::ConnectionType {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Wifi => 0.into_dart(),
            Self::Cellular => 1.into_dart(),
            Self::Ethernet => 2.into_dart(),
            Self::Vpn => 3.into_dart(),
            Self::Bluetooth => 4.into_dart(),
            Self::Unknown => 5.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::models::net_info::ConnectionType
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::models::net_info::ConnectionType>
    for crate::api::models::net_info::ConnectionType
{
    fn into_into_dart(self) -> crate::api::models::net_info::ConnectionType {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::models::report::LatencyStats {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.latency_ms.into_into_dart().into_dart(),
            self.jitter_ms.into_into_dart().into_dart(),
            self.packet_loss_percent.into_into_dart().into_dart(),
            self.min_latency_ms.into_into_dart().into_dart(),
            self.avg_latency_ms.into_into_dart().into_dart(),
            self.max_latency_ms.into_into_dart().into_dart(),
            self.stability_score.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::models::report::LatencyStats
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::models::report::LatencyStats>
    for crate::api::models::report::LatencyStats
{
    fn into_into_dart(self) -> crate::api::models::report::LatencyStats {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::models::config::NetworkConfiguration {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.targets.into_into_dart().into_dart(),
            self.check_interval_ms.into_into_dart().into_dart(),
            self.quality_threshold.into_into_dart().into_dart(),
            self.security.into_into_dart().into_dart(),
            self.resilience.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::models::config::NetworkConfiguration
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::models::config::NetworkConfiguration>
    for crate::api::models::config::NetworkConfiguration
{
    fn into_into_dart(self) -> crate::api::models::config::NetworkConfiguration {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::models::report::NetworkReport {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.timestamp_ms.into_into_dart().into_dart(),
            self.status.into_into_dart().into_dart(),
            self.connection_type.into_into_dart().into_dart(),
            self.security_flags.into_into_dart().into_dart(),
            self.target_reports.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::models::report::NetworkReport
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::models::report::NetworkReport>
    for crate::api::models::report::NetworkReport
{
    fn into_into_dart(self) -> crate::api::models::report::NetworkReport {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::models::report::NetworkStatus {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.is_connected.into_into_dart().into_dart(),
            self.quality.into_into_dart().into_dart(),
            self.latency_stats.into_into_dart().into_dart(),
            self.winner_target.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::models::report::NetworkStatus
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::models::report::NetworkStatus>
    for crate::api::models::report::NetworkStatus
{
    fn into_into_dart(self) -> crate::api::models::report::NetworkStatus {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::models::target::NetworkTarget {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.label.into_into_dart().into_dart(),
            self.host.into_into_dart().into_dart(),
            self.port.into_into_dart().into_dart(),
            self.protocol.into_into_dart().into_dart(),
            self.timeout_ms.into_into_dart().into_dart(),
            self.priority.into_into_dart().into_dart(),
            self.is_essential.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::models::target::NetworkTarget
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::models::target::NetworkTarget>
    for crate::api::models::target::NetworkTarget
{
    fn into_into_dart(self) -> crate::api::models::target::NetworkTarget {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::models::config::QualityThresholds {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.excellent.into_into_dart().into_dart(),
            self.great.into_into_dart().into_dart(),
            self.good.into_into_dart().into_dart(),
            self.moderate.into_into_dart().into_dart(),
            self.poor.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::models::config::QualityThresholds
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::models::config::QualityThresholds>
    for crate::api::models::config::QualityThresholds
{
    fn into_into_dart(self) -> crate::api::models::config::QualityThresholds {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::models::config::ResilienceConfig {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.strategy.into_into_dart().into_dart(),
            self.circuit_breaker_threshold.into_into_dart().into_dart(),
            self.num_jitter_samples.into_into_dart().into_dart(),
            self.jitter_threshold_percent.into_into_dart().into_dart(),
            self.stability_thershold.into_into_dart().into_dart(),
            self.critical_packet_loss_precent
                .into_into_dart()
                .into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::models::config::ResilienceConfig
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::models::config::ResilienceConfig>
    for crate::api::models::config::ResilienceConfig
{
    fn into_into_dart(self) -> crate::api::models::config::ResilienceConfig {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::models::config::SecurityConfig {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.block_vpn.into_into_dart().into_dart(),
            self.detect_dns_hijack.into_into_dart().into_dart(),
            self.allowed_interfaces.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::models::config::SecurityConfig
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::models::config::SecurityConfig>
    for crate::api::models::config::SecurityConfig
{
    fn into_into_dart(self) -> crate::api::models::config::SecurityConfig {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::models::net_info::SecurityFlags {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.is_vpn_detected.into_into_dart().into_dart(),
            self.is_dns_spoofed.into_into_dart().into_dart(),
            self.is_proxy_detected.into_into_dart().into_dart(),
            self.interface_name.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::models::net_info::SecurityFlags
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::models::net_info::SecurityFlags>
    for crate::api::models::net_info::SecurityFlags
{
    fn into_into_dart(self) -> crate::api::models::net_info::SecurityFlags {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::models::target::TargetProtocol {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Tcp => 0.into_dart(),
            Self::Udp => 1.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::models::target::TargetProtocol
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::models::target::TargetProtocol>
    for crate::api::models::target::TargetProtocol
{
    fn into_into_dart(self) -> crate::api::models::target::TargetProtocol {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::models::report::TargetReport {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.label.into_into_dart().into_dart(),
            self.success.into_into_dart().into_dart(),
            self.latency_ms.into_into_dart().into_dart(),
            self.error.into_into_dart().into_dart(),
            self.is_essential.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::models::report::TargetReport
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::models::report::TargetReport>
    for crate::api::models::report::TargetReport
{
    fn into_into_dart(self) -> crate::api::models::report::TargetReport {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::models::net_info::TraceHop {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.hop_number.into_into_dart().into_dart(),
            self.ip_address.into_into_dart().into_dart(),
            self.hostname.into_into_dart().into_dart(),
            self.latency_ms.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::models::net_info::TraceHop
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::models::net_info::TraceHop>
    for crate::api::models::net_info::TraceHop
{
    fn into_into_dart(self) -> crate::api::models::net_info::TraceHop {
        self
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for crate::api::models::net_info::CaptivePortalStatus {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_captive_portal, serializer);
        <Option<String>>::sse_encode(self.redirect_url, serializer);
    }
}

impl SseEncode for crate::api::models::config::CheckStrategy {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::models::config::CheckStrategy::Race => 0,
                crate::api::models::config::CheckStrategy::Consensus => 1,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::models::config::ConnectionQuality {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::models::config::ConnectionQuality::Excellent => 0,
                crate::api::models::config::ConnectionQuality::Great => 1,
                crate::api::models::config::ConnectionQuality::Good => 2,
                crate::api::models::config::ConnectionQuality::Moderate => 3,
                crate::api::models::config::ConnectionQuality::Poor => 4,
                crate::api::models::config::ConnectionQuality::Unstable => 5,
                crate::api::models::config::ConnectionQuality::Offline => 6,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::models::net_info::ConnectionType {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::models::net_info::ConnectionType::Wifi => 0,
                crate::api::models::net_info::ConnectionType::Cellular => 1,
                crate::api::models::net_info::ConnectionType::Ethernet => 2,
                crate::api::models::net_info::ConnectionType::Vpn => 3,
                crate::api::models::net_info::ConnectionType::Bluetooth => 4,
                crate::api::models::net_info::ConnectionType::Unknown => 5,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for f32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_f32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for f64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_f64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for crate::api::models::report::LatencyStats {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u64>::sse_encode(self.latency_ms, serializer);
        <u64>::sse_encode(self.jitter_ms, serializer);
        <f32>::sse_encode(self.packet_loss_percent, serializer);
        <Option<u64>>::sse_encode(self.min_latency_ms, serializer);
        <Option<u64>>::sse_encode(self.avg_latency_ms, serializer);
        <Option<u64>>::sse_encode(self.max_latency_ms, serializer);
        <u8>::sse_encode(self.stability_score, serializer);
    }
}

impl SseEncode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <String>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::models::target::NetworkTarget> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::models::target::NetworkTarget>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u64>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::models::report::TargetReport> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::models::report::TargetReport>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::models::net_info::TraceHop> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::models::net_info::TraceHop>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for crate::api::models::config::NetworkConfiguration {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<crate::api::models::target::NetworkTarget>>::sse_encode(self.targets, serializer);
        <u64>::sse_encode(self.check_interval_ms, serializer);
        <crate::api::models::config::QualityThresholds>::sse_encode(
            self.quality_threshold,
            serializer,
        );
        <crate::api::models::config::SecurityConfig>::sse_encode(self.security, serializer);
        <crate::api::models::config::ResilienceConfig>::sse_encode(self.resilience, serializer);
    }
}

impl SseEncode for crate::api::models::report::NetworkReport {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u64>::sse_encode(self.timestamp_ms, serializer);
        <crate::api::models::report::NetworkStatus>::sse_encode(self.status, serializer);
        <crate::api::models::net_info::ConnectionType>::sse_encode(
            self.connection_type,
            serializer,
        );
        <crate::api::models::net_info::SecurityFlags>::sse_encode(self.security_flags, serializer);
        <Vec<crate::api::models::report::TargetReport>>::sse_encode(
            self.target_reports,
            serializer,
        );
    }
}

impl SseEncode for crate::api::models::report::NetworkStatus {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_connected, serializer);
        <crate::api::models::config::ConnectionQuality>::sse_encode(self.quality, serializer);
        <crate::api::models::report::LatencyStats>::sse_encode(self.latency_stats, serializer);
        <String>::sse_encode(self.winner_target, serializer);
    }
}

impl SseEncode for crate::api::models::target::NetworkTarget {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.label, serializer);
        <String>::sse_encode(self.host, serializer);
        <u16>::sse_encode(self.port, serializer);
        <crate::api::models::target::TargetProtocol>::sse_encode(self.protocol, serializer);
        <u64>::sse_encode(self.timeout_ms, serializer);
        <u8>::sse_encode(self.priority, serializer);
        <bool>::sse_encode(self.is_essential, serializer);
    }
}

impl SseEncode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <String>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<f64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <f64>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<u64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <u64>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for crate::api::models::config::QualityThresholds {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u64>::sse_encode(self.excellent, serializer);
        <u64>::sse_encode(self.great, serializer);
        <u64>::sse_encode(self.good, serializer);
        <u64>::sse_encode(self.moderate, serializer);
        <u64>::sse_encode(self.poor, serializer);
    }
}

impl SseEncode for (Option<u64>, Option<u64>, Option<u64>, Option<f64>) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Option<u64>>::sse_encode(self.0, serializer);
        <Option<u64>>::sse_encode(self.1, serializer);
        <Option<u64>>::sse_encode(self.2, serializer);
        <Option<f64>>::sse_encode(self.3, serializer);
    }
}

impl SseEncode
    for (
        crate::api::models::net_info::SecurityFlags,
        crate::api::models::net_info::ConnectionType,
    )
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::api::models::net_info::SecurityFlags>::sse_encode(self.0, serializer);
        <crate::api::models::net_info::ConnectionType>::sse_encode(self.1, serializer);
    }
}

impl SseEncode for crate::api::models::config::ResilienceConfig {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::api::models::config::CheckStrategy>::sse_encode(self.strategy, serializer);
        <u8>::sse_encode(self.circuit_breaker_threshold, serializer);
        <u8>::sse_encode(self.num_jitter_samples, serializer);
        <f64>::sse_encode(self.jitter_threshold_percent, serializer);
        <u8>::sse_encode(self.stability_thershold, serializer);
        <f32>::sse_encode(self.critical_packet_loss_precent, serializer);
    }
}

impl SseEncode for crate::api::models::config::SecurityConfig {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.block_vpn, serializer);
        <bool>::sse_encode(self.detect_dns_hijack, serializer);
        <Vec<String>>::sse_encode(self.allowed_interfaces, serializer);
    }
}

impl SseEncode for crate::api::models::net_info::SecurityFlags {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_vpn_detected, serializer);
        <bool>::sse_encode(self.is_dns_spoofed, serializer);
        <bool>::sse_encode(self.is_proxy_detected, serializer);
        <String>::sse_encode(self.interface_name, serializer);
    }
}

impl SseEncode for crate::api::models::target::TargetProtocol {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::models::target::TargetProtocol::Tcp => 0,
                crate::api::models::target::TargetProtocol::Udp => 1,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::models::report::TargetReport {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.label, serializer);
        <bool>::sse_encode(self.success, serializer);
        <u64>::sse_encode(self.latency_ms, serializer);
        <Option<String>>::sse_encode(self.error, serializer);
        <bool>::sse_encode(self.is_essential, serializer);
    }
}

impl SseEncode for crate::api::models::net_info::TraceHop {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u8>::sse_encode(self.hop_number, serializer);
        <String>::sse_encode(self.ip_address, serializer);
        <Option<String>>::sse_encode(self.hostname, serializer);
        <Option<u64>>::sse_encode(self.latency_ms, serializer);
    }
}

impl SseEncode for u16 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u16::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.11.1.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.11.1.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::wasm_bindgen;
    use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();
}
#[cfg(target_family = "wasm")]
pub use web::*;
