// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::needless_borrow
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.11.1";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = 967474185;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__engine___calculate_jitter_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "_calculate_jitter",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_latencies = <Vec<u64>>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok =
                        Result::<_, ()>::Ok(crate::api::engine::_calculate_jitter(&api_latencies))?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__utils__check_for_captive_portal_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "check_for_captive_portal",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_timeout_ms = <u64>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, ()>(
                    (move || async move {
                        let output_ok = Result::<_, ()>::Ok(
                            crate::api::utils::check_for_captive_portal(api_timeout_ms).await,
                        )?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__engine__check_network_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "check_network",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_config =
                <crate::api::models::NetwrokConfiguration>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, ()>(
                    (move || async move {
                        let output_ok = Result::<_, ()>::Ok(
                            crate::api::engine::check_network(api_config).await,
                        )?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__utils__detect_network_metadata_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "detect_network_metadata",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok =
                        Result::<_, ()>::Ok(crate::api::utils::detect_network_metadata())?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__utils__evaluate_quality_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "evaluate_quality",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_latency = <u64>::sse_decode(&mut deserializer);
            let api_threshold =
                <crate::api::models::QualityThresholds>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok(crate::api::utils::evaluate_quality(
                        api_latency,
                        &api_threshold,
                    ))?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__models__netwrok_configuration_default_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "netwrok_configuration_default",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok =
                        Result::<_, ()>::Ok(crate::api::models::NetwrokConfiguration::default())?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__models__quality_thresholds_default_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "quality_thresholds_default",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok =
                        Result::<_, ()>::Ok(crate::api::models::QualityThresholds::default())?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__utils__scan_local_network_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "scan_local_network",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_subnet = <String>::sse_decode(&mut deserializer);
            let api_scan_port = <u16>::sse_decode(&mut deserializer);
            let api_timeout_ms = <u64>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, ()>(
                    (move || async move {
                        let output_ok = Result::<_, ()>::Ok(
                            crate::api::utils::scan_local_network(
                                api_subnet,
                                api_scan_port,
                                api_timeout_ms,
                            )
                            .await,
                        )?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__utils__trace_route_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "trace_route",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_host = <String>::sse_decode(&mut deserializer);
            let api_max_hops = <u8>::sse_decode(&mut deserializer);
            let api_timeout_per_hop_ms = <u64>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, ()>(
                    (move || async move {
                        let output_ok = Result::<_, ()>::Ok(
                            crate::api::utils::trace_route(
                                api_host,
                                api_max_hops,
                                api_timeout_per_hop_ms,
                            )
                            .await,
                        )?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}

// Section: dart2rust

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for crate::api::models::CaptivePortalStatus {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_isCaptivePortal = <bool>::sse_decode(deserializer);
        let mut var_redirectUrl = <Option<String>>::sse_decode(deserializer);
        return crate::api::models::CaptivePortalStatus {
            is_captive_portal: var_isCaptivePortal,
            redirect_url: var_redirectUrl,
        };
    }
}

impl SseDecode for crate::api::models::CheckStrategy {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::models::CheckStrategy::Race,
            1 => crate::api::models::CheckStrategy::Consensus,
            _ => unreachable!("Invalid variant for CheckStrategy: {}", inner),
        };
    }
}

impl SseDecode for crate::api::models::ConnectionQuality {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::models::ConnectionQuality::Excellent,
            1 => crate::api::models::ConnectionQuality::Great,
            2 => crate::api::models::ConnectionQuality::Good,
            3 => crate::api::models::ConnectionQuality::Moderate,
            4 => crate::api::models::ConnectionQuality::Poor,
            5 => crate::api::models::ConnectionQuality::Unstable,
            6 => crate::api::models::ConnectionQuality::Dead,
            _ => unreachable!("Invalid variant for ConnectionQuality: {}", inner),
        };
    }
}

impl SseDecode for crate::api::models::ConnectionType {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::models::ConnectionType::Wifi,
            1 => crate::api::models::ConnectionType::Cellular,
            2 => crate::api::models::ConnectionType::Ethernet,
            3 => crate::api::models::ConnectionType::Vpn,
            4 => crate::api::models::ConnectionType::Bluetooth,
            5 => crate::api::models::ConnectionType::Unknown,
            _ => unreachable!("Invalid variant for ConnectionType: {}", inner),
        };
    }
}

impl SseDecode for f64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_f64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for Vec<crate::api::models::LocalDevice> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<crate::api::models::LocalDevice>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::models::NetworkTarget> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<crate::api::models::NetworkTarget>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<u64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<u64>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::models::TargetReport> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<crate::api::models::TargetReport>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::models::TraceHop> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<crate::api::models::TraceHop>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for crate::api::models::LocalDevice {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_ipAddress = <String>::sse_decode(deserializer);
        let mut var_hostname = <Option<String>>::sse_decode(deserializer);
        let mut var_macAddress = <Option<String>>::sse_decode(deserializer);
        return crate::api::models::LocalDevice {
            ip_address: var_ipAddress,
            hostname: var_hostname,
            mac_address: var_macAddress,
        };
    }
}

impl SseDecode for crate::api::models::NetworkMetadata {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_isVpn = <bool>::sse_decode(deserializer);
        let mut var_interfaceName = <String>::sse_decode(deserializer);
        return crate::api::models::NetworkMetadata {
            is_vpn: var_isVpn,
            interface_name: var_interfaceName,
        };
    }
}

impl SseDecode for crate::api::models::NetworkReport {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_timestampMs = <u64>::sse_decode(deserializer);
        let mut var_status = <crate::api::models::NetworkStatus>::sse_decode(deserializer);
        let mut var_connectionType = <crate::api::models::ConnectionType>::sse_decode(deserializer);
        let mut var_metadata = <crate::api::models::NetworkMetadata>::sse_decode(deserializer);
        let mut var_targetReports =
            <Vec<crate::api::models::TargetReport>>::sse_decode(deserializer);
        return crate::api::models::NetworkReport {
            timestamp_ms: var_timestampMs,
            status: var_status,
            connection_type: var_connectionType,
            metadata: var_metadata,
            target_reports: var_targetReports,
        };
    }
}

impl SseDecode for crate::api::models::NetworkStatus {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_isConnected = <bool>::sse_decode(deserializer);
        let mut var_quality = <crate::api::models::ConnectionQuality>::sse_decode(deserializer);
        let mut var_latencyMs = <u64>::sse_decode(deserializer);
        let mut var_winnerTarget = <String>::sse_decode(deserializer);
        let mut var_minLatencyMs = <Option<u64>>::sse_decode(deserializer);
        let mut var_maxLatencyMs = <Option<u64>>::sse_decode(deserializer);
        let mut var_meanLatencyMs = <Option<u64>>::sse_decode(deserializer);
        let mut var_stdDevLatencyMs = <Option<f64>>::sse_decode(deserializer);
        return crate::api::models::NetworkStatus {
            is_connected: var_isConnected,
            quality: var_quality,
            latency_ms: var_latencyMs,
            winner_target: var_winnerTarget,
            min_latency_ms: var_minLatencyMs,
            max_latency_ms: var_maxLatencyMs,
            mean_latency_ms: var_meanLatencyMs,
            std_dev_latency_ms: var_stdDevLatencyMs,
        };
    }
}

impl SseDecode for crate::api::models::NetworkTarget {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_label = <String>::sse_decode(deserializer);
        let mut var_host = <String>::sse_decode(deserializer);
        let mut var_port = <u16>::sse_decode(deserializer);
        let mut var_protocol = <crate::api::models::TargetProtocol>::sse_decode(deserializer);
        let mut var_timeoutMs = <u64>::sse_decode(deserializer);
        let mut var_priority = <u8>::sse_decode(deserializer);
        let mut var_isEssential = <bool>::sse_decode(deserializer);
        return crate::api::models::NetworkTarget {
            label: var_label,
            host: var_host,
            port: var_port,
            protocol: var_protocol,
            timeout_ms: var_timeoutMs,
            priority: var_priority,
            is_essential: var_isEssential,
        };
    }
}

impl SseDecode for crate::api::models::NetwrokConfiguration {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_targets = <Vec<crate::api::models::NetworkTarget>>::sse_decode(deserializer);
        let mut var_checkStrategy = <crate::api::models::CheckStrategy>::sse_decode(deserializer);
        let mut var_qualityThreshold =
            <crate::api::models::QualityThresholds>::sse_decode(deserializer);
        let mut var_checkIntervalMs = <u64>::sse_decode(deserializer);
        let mut var_blockRequestWhenPoor = <bool>::sse_decode(deserializer);
        let mut var_numJitterSamples = <u8>::sse_decode(deserializer);
        let mut var_jitterThresholdPercent = <f64>::sse_decode(deserializer);
        return crate::api::models::NetwrokConfiguration {
            targets: var_targets,
            check_strategy: var_checkStrategy,
            quality_threshold: var_qualityThreshold,
            check_interval_ms: var_checkIntervalMs,
            block_request_when_poor: var_blockRequestWhenPoor,
            num_jitter_samples: var_numJitterSamples,
            jitter_threshold_percent: var_jitterThresholdPercent,
        };
    }
}

impl SseDecode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<String>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<f64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<f64>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<u64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<u64>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for crate::api::models::QualityThresholds {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_excellent = <u64>::sse_decode(deserializer);
        let mut var_great = <u64>::sse_decode(deserializer);
        let mut var_good = <u64>::sse_decode(deserializer);
        let mut var_moderate = <u64>::sse_decode(deserializer);
        let mut var_poor = <u64>::sse_decode(deserializer);
        return crate::api::models::QualityThresholds {
            excellent: var_excellent,
            great: var_great,
            good: var_good,
            moderate: var_moderate,
            poor: var_poor,
        };
    }
}

impl SseDecode
    for (
        crate::api::models::NetworkMetadata,
        crate::api::models::ConnectionType,
    )
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_field0 = <crate::api::models::NetworkMetadata>::sse_decode(deserializer);
        let mut var_field1 = <crate::api::models::ConnectionType>::sse_decode(deserializer);
        return (var_field0, var_field1);
    }
}

impl SseDecode for (Option<u64>, Option<u64>, Option<u64>, Option<f64>) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_field0 = <Option<u64>>::sse_decode(deserializer);
        let mut var_field1 = <Option<u64>>::sse_decode(deserializer);
        let mut var_field2 = <Option<u64>>::sse_decode(deserializer);
        let mut var_field3 = <Option<f64>>::sse_decode(deserializer);
        return (var_field0, var_field1, var_field2, var_field3);
    }
}

impl SseDecode for crate::api::models::TargetProtocol {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::models::TargetProtocol::Tcp,
            1 => crate::api::models::TargetProtocol::Udp,
            _ => unreachable!("Invalid variant for TargetProtocol: {}", inner),
        };
    }
}

impl SseDecode for crate::api::models::TargetReport {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_label = <String>::sse_decode(deserializer);
        let mut var_success = <bool>::sse_decode(deserializer);
        let mut var_latencyMs = <Option<u64>>::sse_decode(deserializer);
        let mut var_error = <Option<String>>::sse_decode(deserializer);
        let mut var_isEssential = <bool>::sse_decode(deserializer);
        return crate::api::models::TargetReport {
            label: var_label,
            success: var_success,
            latency_ms: var_latencyMs,
            error: var_error,
            is_essential: var_isEssential,
        };
    }
}

impl SseDecode for crate::api::models::TraceHop {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_hopNumber = <u8>::sse_decode(deserializer);
        let mut var_ipAddress = <String>::sse_decode(deserializer);
        let mut var_hostname = <Option<String>>::sse_decode(deserializer);
        let mut var_latencyMs = <Option<u64>>::sse_decode(deserializer);
        return crate::api::models::TraceHop {
            hop_number: var_hopNumber,
            ip_address: var_ipAddress,
            hostname: var_hostname,
            latency_ms: var_latencyMs,
        };
    }
}

impl SseDecode for u16 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u16::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => wire__crate__api__engine___calculate_jitter_impl(port, ptr, rust_vec_len, data_len),
        2 => wire__crate__api__utils__check_for_captive_portal_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        3 => wire__crate__api__engine__check_network_impl(port, ptr, rust_vec_len, data_len),
        4 => {
            wire__crate__api__utils__detect_network_metadata_impl(port, ptr, rust_vec_len, data_len)
        }
        5 => wire__crate__api__utils__evaluate_quality_impl(port, ptr, rust_vec_len, data_len),
        6 => wire__crate__api__models__netwrok_configuration_default_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        7 => wire__crate__api__models__quality_thresholds_default_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        8 => wire__crate__api__utils__scan_local_network_impl(port, ptr, rust_vec_len, data_len),
        9 => wire__crate__api__utils__trace_route_impl(port, ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::models::CaptivePortalStatus {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.is_captive_portal.into_into_dart().into_dart(),
            self.redirect_url.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::models::CaptivePortalStatus
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::models::CaptivePortalStatus>
    for crate::api::models::CaptivePortalStatus
{
    fn into_into_dart(self) -> crate::api::models::CaptivePortalStatus {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::models::CheckStrategy {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Race => 0.into_dart(),
            Self::Consensus => 1.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::models::CheckStrategy
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::models::CheckStrategy>
    for crate::api::models::CheckStrategy
{
    fn into_into_dart(self) -> crate::api::models::CheckStrategy {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::models::ConnectionQuality {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Excellent => 0.into_dart(),
            Self::Great => 1.into_dart(),
            Self::Good => 2.into_dart(),
            Self::Moderate => 3.into_dart(),
            Self::Poor => 4.into_dart(),
            Self::Unstable => 5.into_dart(),
            Self::Dead => 6.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::models::ConnectionQuality
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::models::ConnectionQuality>
    for crate::api::models::ConnectionQuality
{
    fn into_into_dart(self) -> crate::api::models::ConnectionQuality {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::models::ConnectionType {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Wifi => 0.into_dart(),
            Self::Cellular => 1.into_dart(),
            Self::Ethernet => 2.into_dart(),
            Self::Vpn => 3.into_dart(),
            Self::Bluetooth => 4.into_dart(),
            Self::Unknown => 5.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::models::ConnectionType
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::models::ConnectionType>
    for crate::api::models::ConnectionType
{
    fn into_into_dart(self) -> crate::api::models::ConnectionType {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::models::LocalDevice {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.ip_address.into_into_dart().into_dart(),
            self.hostname.into_into_dart().into_dart(),
            self.mac_address.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::models::LocalDevice
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::models::LocalDevice>
    for crate::api::models::LocalDevice
{
    fn into_into_dart(self) -> crate::api::models::LocalDevice {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::models::NetworkMetadata {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.is_vpn.into_into_dart().into_dart(),
            self.interface_name.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::models::NetworkMetadata
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::models::NetworkMetadata>
    for crate::api::models::NetworkMetadata
{
    fn into_into_dart(self) -> crate::api::models::NetworkMetadata {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::models::NetworkReport {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.timestamp_ms.into_into_dart().into_dart(),
            self.status.into_into_dart().into_dart(),
            self.connection_type.into_into_dart().into_dart(),
            self.metadata.into_into_dart().into_dart(),
            self.target_reports.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::models::NetworkReport
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::models::NetworkReport>
    for crate::api::models::NetworkReport
{
    fn into_into_dart(self) -> crate::api::models::NetworkReport {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::models::NetworkStatus {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.is_connected.into_into_dart().into_dart(),
            self.quality.into_into_dart().into_dart(),
            self.latency_ms.into_into_dart().into_dart(),
            self.winner_target.into_into_dart().into_dart(),
            self.min_latency_ms.into_into_dart().into_dart(),
            self.max_latency_ms.into_into_dart().into_dart(),
            self.mean_latency_ms.into_into_dart().into_dart(),
            self.std_dev_latency_ms.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::models::NetworkStatus
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::models::NetworkStatus>
    for crate::api::models::NetworkStatus
{
    fn into_into_dart(self) -> crate::api::models::NetworkStatus {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::models::NetworkTarget {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.label.into_into_dart().into_dart(),
            self.host.into_into_dart().into_dart(),
            self.port.into_into_dart().into_dart(),
            self.protocol.into_into_dart().into_dart(),
            self.timeout_ms.into_into_dart().into_dart(),
            self.priority.into_into_dart().into_dart(),
            self.is_essential.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::models::NetworkTarget
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::models::NetworkTarget>
    for crate::api::models::NetworkTarget
{
    fn into_into_dart(self) -> crate::api::models::NetworkTarget {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::models::NetwrokConfiguration {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.targets.into_into_dart().into_dart(),
            self.check_strategy.into_into_dart().into_dart(),
            self.quality_threshold.into_into_dart().into_dart(),
            self.check_interval_ms.into_into_dart().into_dart(),
            self.block_request_when_poor.into_into_dart().into_dart(),
            self.num_jitter_samples.into_into_dart().into_dart(),
            self.jitter_threshold_percent.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::models::NetwrokConfiguration
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::models::NetwrokConfiguration>
    for crate::api::models::NetwrokConfiguration
{
    fn into_into_dart(self) -> crate::api::models::NetwrokConfiguration {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::models::QualityThresholds {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.excellent.into_into_dart().into_dart(),
            self.great.into_into_dart().into_dart(),
            self.good.into_into_dart().into_dart(),
            self.moderate.into_into_dart().into_dart(),
            self.poor.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::models::QualityThresholds
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::models::QualityThresholds>
    for crate::api::models::QualityThresholds
{
    fn into_into_dart(self) -> crate::api::models::QualityThresholds {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::models::TargetProtocol {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Tcp => 0.into_dart(),
            Self::Udp => 1.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::models::TargetProtocol
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::models::TargetProtocol>
    for crate::api::models::TargetProtocol
{
    fn into_into_dart(self) -> crate::api::models::TargetProtocol {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::models::TargetReport {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.label.into_into_dart().into_dart(),
            self.success.into_into_dart().into_dart(),
            self.latency_ms.into_into_dart().into_dart(),
            self.error.into_into_dart().into_dart(),
            self.is_essential.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::models::TargetReport
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::models::TargetReport>
    for crate::api::models::TargetReport
{
    fn into_into_dart(self) -> crate::api::models::TargetReport {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::models::TraceHop {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.hop_number.into_into_dart().into_dart(),
            self.ip_address.into_into_dart().into_dart(),
            self.hostname.into_into_dart().into_dart(),
            self.latency_ms.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::models::TraceHop {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::models::TraceHop>
    for crate::api::models::TraceHop
{
    fn into_into_dart(self) -> crate::api::models::TraceHop {
        self
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for crate::api::models::CaptivePortalStatus {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_captive_portal, serializer);
        <Option<String>>::sse_encode(self.redirect_url, serializer);
    }
}

impl SseEncode for crate::api::models::CheckStrategy {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::models::CheckStrategy::Race => 0,
                crate::api::models::CheckStrategy::Consensus => 1,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::models::ConnectionQuality {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::models::ConnectionQuality::Excellent => 0,
                crate::api::models::ConnectionQuality::Great => 1,
                crate::api::models::ConnectionQuality::Good => 2,
                crate::api::models::ConnectionQuality::Moderate => 3,
                crate::api::models::ConnectionQuality::Poor => 4,
                crate::api::models::ConnectionQuality::Unstable => 5,
                crate::api::models::ConnectionQuality::Dead => 6,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::models::ConnectionType {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::models::ConnectionType::Wifi => 0,
                crate::api::models::ConnectionType::Cellular => 1,
                crate::api::models::ConnectionType::Ethernet => 2,
                crate::api::models::ConnectionType::Vpn => 3,
                crate::api::models::ConnectionType::Bluetooth => 4,
                crate::api::models::ConnectionType::Unknown => 5,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for f64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_f64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for Vec<crate::api::models::LocalDevice> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::models::LocalDevice>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::models::NetworkTarget> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::models::NetworkTarget>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u64>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::models::TargetReport> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::models::TargetReport>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::models::TraceHop> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::models::TraceHop>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for crate::api::models::LocalDevice {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.ip_address, serializer);
        <Option<String>>::sse_encode(self.hostname, serializer);
        <Option<String>>::sse_encode(self.mac_address, serializer);
    }
}

impl SseEncode for crate::api::models::NetworkMetadata {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_vpn, serializer);
        <String>::sse_encode(self.interface_name, serializer);
    }
}

impl SseEncode for crate::api::models::NetworkReport {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u64>::sse_encode(self.timestamp_ms, serializer);
        <crate::api::models::NetworkStatus>::sse_encode(self.status, serializer);
        <crate::api::models::ConnectionType>::sse_encode(self.connection_type, serializer);
        <crate::api::models::NetworkMetadata>::sse_encode(self.metadata, serializer);
        <Vec<crate::api::models::TargetReport>>::sse_encode(self.target_reports, serializer);
    }
}

impl SseEncode for crate::api::models::NetworkStatus {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_connected, serializer);
        <crate::api::models::ConnectionQuality>::sse_encode(self.quality, serializer);
        <u64>::sse_encode(self.latency_ms, serializer);
        <String>::sse_encode(self.winner_target, serializer);
        <Option<u64>>::sse_encode(self.min_latency_ms, serializer);
        <Option<u64>>::sse_encode(self.max_latency_ms, serializer);
        <Option<u64>>::sse_encode(self.mean_latency_ms, serializer);
        <Option<f64>>::sse_encode(self.std_dev_latency_ms, serializer);
    }
}

impl SseEncode for crate::api::models::NetworkTarget {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.label, serializer);
        <String>::sse_encode(self.host, serializer);
        <u16>::sse_encode(self.port, serializer);
        <crate::api::models::TargetProtocol>::sse_encode(self.protocol, serializer);
        <u64>::sse_encode(self.timeout_ms, serializer);
        <u8>::sse_encode(self.priority, serializer);
        <bool>::sse_encode(self.is_essential, serializer);
    }
}

impl SseEncode for crate::api::models::NetwrokConfiguration {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<crate::api::models::NetworkTarget>>::sse_encode(self.targets, serializer);
        <crate::api::models::CheckStrategy>::sse_encode(self.check_strategy, serializer);
        <crate::api::models::QualityThresholds>::sse_encode(self.quality_threshold, serializer);
        <u64>::sse_encode(self.check_interval_ms, serializer);
        <bool>::sse_encode(self.block_request_when_poor, serializer);
        <u8>::sse_encode(self.num_jitter_samples, serializer);
        <f64>::sse_encode(self.jitter_threshold_percent, serializer);
    }
}

impl SseEncode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <String>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<f64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <f64>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<u64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <u64>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for crate::api::models::QualityThresholds {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u64>::sse_encode(self.excellent, serializer);
        <u64>::sse_encode(self.great, serializer);
        <u64>::sse_encode(self.good, serializer);
        <u64>::sse_encode(self.moderate, serializer);
        <u64>::sse_encode(self.poor, serializer);
    }
}

impl SseEncode
    for (
        crate::api::models::NetworkMetadata,
        crate::api::models::ConnectionType,
    )
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::api::models::NetworkMetadata>::sse_encode(self.0, serializer);
        <crate::api::models::ConnectionType>::sse_encode(self.1, serializer);
    }
}

impl SseEncode for (Option<u64>, Option<u64>, Option<u64>, Option<f64>) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Option<u64>>::sse_encode(self.0, serializer);
        <Option<u64>>::sse_encode(self.1, serializer);
        <Option<u64>>::sse_encode(self.2, serializer);
        <Option<f64>>::sse_encode(self.3, serializer);
    }
}

impl SseEncode for crate::api::models::TargetProtocol {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::models::TargetProtocol::Tcp => 0,
                crate::api::models::TargetProtocol::Udp => 1,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::models::TargetReport {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.label, serializer);
        <bool>::sse_encode(self.success, serializer);
        <Option<u64>>::sse_encode(self.latency_ms, serializer);
        <Option<String>>::sse_encode(self.error, serializer);
        <bool>::sse_encode(self.is_essential, serializer);
    }
}

impl SseEncode for crate::api::models::TraceHop {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u8>::sse_encode(self.hop_number, serializer);
        <String>::sse_encode(self.ip_address, serializer);
        <Option<String>>::sse_encode(self.hostname, serializer);
        <Option<u64>>::sse_encode(self.latency_ms, serializer);
    }
}

impl SseEncode for u16 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u16::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.11.1.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.11.1.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::wasm_bindgen;
    use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();
}
#[cfg(target_family = "wasm")]
pub use web::*;
