// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: public_member_api_docs, unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'dart:async';
import 'dart:convert';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

import 'api/analysis/quality.dart';
import 'api/analysis/stats.dart';
import 'api/engine.dart';
import 'api/engine/sampler.dart';
import 'api/engine/security.dart';
import 'api/models/config.dart';
import 'api/models/net_info.dart';
import 'api/models/report.dart';
import 'api/models/target.dart';
import 'api/probes/captive_portal.dart';
import 'api/probes/dns.dart';
import 'api/probes/interface.dart';
import 'api/probes/target.dart';
import 'frb_generated.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_NetworkReportPtr => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetworkReport;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_SecurityFlagsResultPtr => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSecurityFlagsResult;

  @protected
  NetworkReport
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetworkReport(
    final dynamic raw,
  );

  @protected
  SecurityFlagsResult
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSecurityFlagsResult(
    final dynamic raw,
  );

  @protected
  NetworkReport
      dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetworkReport(
    final dynamic raw,
  );

  @protected
  SecurityFlagsResult
      dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSecurityFlagsResult(
    final dynamic raw,
  );

  @protected
  NetworkReport
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetworkReport(
    final dynamic raw,
  );

  @protected
  SecurityFlagsResult
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSecurityFlagsResult(
    final dynamic raw,
  );

  @protected
  NetworkReport
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetworkReport(
    final dynamic raw,
  );

  @protected
  SecurityFlagsResult
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSecurityFlagsResult(
    final dynamic raw,
  );

  @protected
  String dco_decode_String(final dynamic raw);

  @protected
  bool dco_decode_bool(final dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(final dynamic raw);

  @protected
  LatencyStats dco_decode_box_autoadd_latency_stats(final dynamic raw);

  @protected
  NativeProbe dco_decode_box_autoadd_native_probe(final dynamic raw);

  @protected
  NetworkConfiguration dco_decode_box_autoadd_network_configuration(
    final dynamic raw,
  );

  @protected
  NetworkTarget dco_decode_box_autoadd_network_target(final dynamic raw);

  @protected
  QualityThresholds dco_decode_box_autoadd_quality_thresholds(
    final dynamic raw,
  );

  @protected
  ResilienceConfig dco_decode_box_autoadd_resilience_config(final dynamic raw);

  @protected
  SecurityConfig dco_decode_box_autoadd_security_config(final dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(final dynamic raw);

  @protected
  WebProbe dco_decode_box_autoadd_web_probe(final dynamic raw);

  @protected
  CaptivePortalStatus dco_decode_captive_portal_status(final dynamic raw);

  @protected
  CheckStrategy dco_decode_check_strategy(final dynamic raw);

  @protected
  ConnectionQuality dco_decode_connection_quality(final dynamic raw);

  @protected
  ConnectionType dco_decode_connection_type(final dynamic raw);

  @protected
  double dco_decode_f_32(final dynamic raw);

  @protected
  double dco_decode_f_64(final dynamic raw);

  @protected
  int dco_decode_i_32(final dynamic raw);

  @protected
  LatencyStats dco_decode_latency_stats(final dynamic raw);

  @protected
  List<NetworkTarget> dco_decode_list_network_target(final dynamic raw);

  @protected
  Uint64List dco_decode_list_prim_u_64_strict(final dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(final dynamic raw);

  @protected
  List<TargetReport> dco_decode_list_target_report(final dynamic raw);

  @protected
  NativeProbe dco_decode_native_probe(final dynamic raw);

  @protected
  NetworkConfiguration dco_decode_network_configuration(final dynamic raw);

  @protected
  NetworkStatus dco_decode_network_status(final dynamic raw);

  @protected
  NetworkTarget dco_decode_network_target(final dynamic raw);

  @protected
  String? dco_decode_opt_String(final dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(final dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(final dynamic raw);

  @protected
  QualityThresholds dco_decode_quality_thresholds(final dynamic raw);

  @protected
  (
    SecurityFlagsResult,
    ConnectionType
  ) dco_decode_record_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_security_flags_result_connection_type(
    final dynamic raw,
  );

  @protected
  (Uint64List, List<TargetReport>)
      dco_decode_record_list_prim_u_64_strict_list_target_report(
    final dynamic raw,
  );

  @protected
  (
    BigInt?,
    BigInt?,
    BigInt?,
    double?
  ) dco_decode_record_opt_box_autoadd_u_64_opt_box_autoadd_u_64_opt_box_autoadd_u_64_opt_box_autoadd_f_64(
    final dynamic raw,
  );

  @protected
  ResilienceConfig dco_decode_resilience_config(final dynamic raw);

  @protected
  SecurityConfig dco_decode_security_config(final dynamic raw);

  @protected
  SecurityFlags dco_decode_security_flags(final dynamic raw);

  @protected
  TargetProtocol dco_decode_target_protocol(final dynamic raw);

  @protected
  TargetReport dco_decode_target_report(final dynamic raw);

  @protected
  int dco_decode_u_16(final dynamic raw);

  @protected
  BigInt dco_decode_u_64(final dynamic raw);

  @protected
  int dco_decode_u_8(final dynamic raw);

  @protected
  void dco_decode_unit(final dynamic raw);

  @protected
  BigInt dco_decode_usize(final dynamic raw);

  @protected
  WebProbe dco_decode_web_probe(final dynamic raw);

  @protected
  NetworkReport
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetworkReport(
    final SseDeserializer deserializer,
  );

  @protected
  SecurityFlagsResult
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSecurityFlagsResult(
    final SseDeserializer deserializer,
  );

  @protected
  NetworkReport
      sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetworkReport(
    final SseDeserializer deserializer,
  );

  @protected
  SecurityFlagsResult
      sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSecurityFlagsResult(
    final SseDeserializer deserializer,
  );

  @protected
  NetworkReport
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetworkReport(
    final SseDeserializer deserializer,
  );

  @protected
  SecurityFlagsResult
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSecurityFlagsResult(
    final SseDeserializer deserializer,
  );

  @protected
  NetworkReport
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetworkReport(
    final SseDeserializer deserializer,
  );

  @protected
  SecurityFlagsResult
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSecurityFlagsResult(
    final SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(final SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(final SseDeserializer deserializer);

  @protected
  double sse_decode_box_autoadd_f_64(final SseDeserializer deserializer);

  @protected
  LatencyStats sse_decode_box_autoadd_latency_stats(
    final SseDeserializer deserializer,
  );

  @protected
  NativeProbe sse_decode_box_autoadd_native_probe(
    final SseDeserializer deserializer,
  );

  @protected
  NetworkConfiguration sse_decode_box_autoadd_network_configuration(
    final SseDeserializer deserializer,
  );

  @protected
  NetworkTarget sse_decode_box_autoadd_network_target(
    final SseDeserializer deserializer,
  );

  @protected
  QualityThresholds sse_decode_box_autoadd_quality_thresholds(
    final SseDeserializer deserializer,
  );

  @protected
  ResilienceConfig sse_decode_box_autoadd_resilience_config(
    final SseDeserializer deserializer,
  );

  @protected
  SecurityConfig sse_decode_box_autoadd_security_config(
    final SseDeserializer deserializer,
  );

  @protected
  BigInt sse_decode_box_autoadd_u_64(final SseDeserializer deserializer);

  @protected
  WebProbe sse_decode_box_autoadd_web_probe(final SseDeserializer deserializer);

  @protected
  CaptivePortalStatus sse_decode_captive_portal_status(
    final SseDeserializer deserializer,
  );

  @protected
  CheckStrategy sse_decode_check_strategy(final SseDeserializer deserializer);

  @protected
  ConnectionQuality sse_decode_connection_quality(
    final SseDeserializer deserializer,
  );

  @protected
  ConnectionType sse_decode_connection_type(final SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(final SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(final SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(final SseDeserializer deserializer);

  @protected
  LatencyStats sse_decode_latency_stats(final SseDeserializer deserializer);

  @protected
  List<NetworkTarget> sse_decode_list_network_target(
    final SseDeserializer deserializer,
  );

  @protected
  Uint64List sse_decode_list_prim_u_64_strict(
    final SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(final SseDeserializer deserializer);

  @protected
  List<TargetReport> sse_decode_list_target_report(
    final SseDeserializer deserializer,
  );

  @protected
  NativeProbe sse_decode_native_probe(final SseDeserializer deserializer);

  @protected
  NetworkConfiguration sse_decode_network_configuration(
    final SseDeserializer deserializer,
  );

  @protected
  NetworkStatus sse_decode_network_status(final SseDeserializer deserializer);

  @protected
  NetworkTarget sse_decode_network_target(final SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(final SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_64(final SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(final SseDeserializer deserializer);

  @protected
  QualityThresholds sse_decode_quality_thresholds(
    final SseDeserializer deserializer,
  );

  @protected
  (
    SecurityFlagsResult,
    ConnectionType
  ) sse_decode_record_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_security_flags_result_connection_type(
    final SseDeserializer deserializer,
  );

  @protected
  (Uint64List, List<TargetReport>)
      sse_decode_record_list_prim_u_64_strict_list_target_report(
    final SseDeserializer deserializer,
  );

  @protected
  (
    BigInt?,
    BigInt?,
    BigInt?,
    double?
  ) sse_decode_record_opt_box_autoadd_u_64_opt_box_autoadd_u_64_opt_box_autoadd_u_64_opt_box_autoadd_f_64(
    final SseDeserializer deserializer,
  );

  @protected
  ResilienceConfig sse_decode_resilience_config(
    final SseDeserializer deserializer,
  );

  @protected
  SecurityConfig sse_decode_security_config(final SseDeserializer deserializer);

  @protected
  SecurityFlags sse_decode_security_flags(final SseDeserializer deserializer);

  @protected
  TargetProtocol sse_decode_target_protocol(final SseDeserializer deserializer);

  @protected
  TargetReport sse_decode_target_report(final SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(final SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(final SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(final SseDeserializer deserializer);

  @protected
  void sse_decode_unit(final SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(final SseDeserializer deserializer);

  @protected
  WebProbe sse_decode_web_probe(final SseDeserializer deserializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetworkReport(
    final NetworkReport self,
    final SseSerializer serializer,
  );

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSecurityFlagsResult(
    final SecurityFlagsResult self,
    final SseSerializer serializer,
  );

  @protected
  void
      sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetworkReport(
    final NetworkReport self,
    final SseSerializer serializer,
  );

  @protected
  void
      sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSecurityFlagsResult(
    final SecurityFlagsResult self,
    final SseSerializer serializer,
  );

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetworkReport(
    final NetworkReport self,
    final SseSerializer serializer,
  );

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSecurityFlagsResult(
    final SecurityFlagsResult self,
    final SseSerializer serializer,
  );

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetworkReport(
    final NetworkReport self,
    final SseSerializer serializer,
  );

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSecurityFlagsResult(
    final SecurityFlagsResult self,
    final SseSerializer serializer,
  );

  @protected
  void sse_encode_String(final String self, final SseSerializer serializer);

  @protected
  void sse_encode_bool(final bool self, final SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_f_64(
    final double self,
    final SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_latency_stats(
    final LatencyStats self,
    final SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_native_probe(
    final NativeProbe self,
    final SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_network_configuration(
    final NetworkConfiguration self,
    final SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_network_target(
    final NetworkTarget self,
    final SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_quality_thresholds(
    final QualityThresholds self,
    final SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_resilience_config(
    final ResilienceConfig self,
    final SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_security_config(
    final SecurityConfig self,
    final SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_64(
    final BigInt self,
    final SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_web_probe(
    final WebProbe self,
    final SseSerializer serializer,
  );

  @protected
  void sse_encode_captive_portal_status(
    final CaptivePortalStatus self,
    final SseSerializer serializer,
  );

  @protected
  void sse_encode_check_strategy(
    final CheckStrategy self,
    final SseSerializer serializer,
  );

  @protected
  void sse_encode_connection_quality(
    final ConnectionQuality self,
    final SseSerializer serializer,
  );

  @protected
  void sse_encode_connection_type(
    final ConnectionType self,
    final SseSerializer serializer,
  );

  @protected
  void sse_encode_f_32(final double self, final SseSerializer serializer);

  @protected
  void sse_encode_f_64(final double self, final SseSerializer serializer);

  @protected
  void sse_encode_i_32(final int self, final SseSerializer serializer);

  @protected
  void sse_encode_latency_stats(
    final LatencyStats self,
    final SseSerializer serializer,
  );

  @protected
  void sse_encode_list_network_target(
    final List<NetworkTarget> self,
    final SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_64_strict(
    final Uint64List self,
    final SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    final Uint8List self,
    final SseSerializer serializer,
  );

  @protected
  void sse_encode_list_target_report(
    final List<TargetReport> self,
    final SseSerializer serializer,
  );

  @protected
  void sse_encode_native_probe(
    final NativeProbe self,
    final SseSerializer serializer,
  );

  @protected
  void sse_encode_network_configuration(
    final NetworkConfiguration self,
    final SseSerializer serializer,
  );

  @protected
  void sse_encode_network_status(
    final NetworkStatus self,
    final SseSerializer serializer,
  );

  @protected
  void sse_encode_network_target(
    final NetworkTarget self,
    final SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(
    final String? self,
    final SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_f_64(
    final double? self,
    final SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_64(
    final BigInt? self,
    final SseSerializer serializer,
  );

  @protected
  void sse_encode_quality_thresholds(
    final QualityThresholds self,
    final SseSerializer serializer,
  );

  @protected
  void
      sse_encode_record_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_security_flags_result_connection_type(
    final (SecurityFlagsResult, ConnectionType) self,
    final SseSerializer serializer,
  );

  @protected
  void sse_encode_record_list_prim_u_64_strict_list_target_report(
    final (Uint64List, List<TargetReport>) self,
    final SseSerializer serializer,
  );

  @protected
  void
      sse_encode_record_opt_box_autoadd_u_64_opt_box_autoadd_u_64_opt_box_autoadd_u_64_opt_box_autoadd_f_64(
    final (BigInt?, BigInt?, BigInt?, double?) self,
    final SseSerializer serializer,
  );

  @protected
  void sse_encode_resilience_config(
    final ResilienceConfig self,
    final SseSerializer serializer,
  );

  @protected
  void sse_encode_security_config(
    final SecurityConfig self,
    final SseSerializer serializer,
  );

  @protected
  void sse_encode_security_flags(
    final SecurityFlags self,
    final SseSerializer serializer,
  );

  @protected
  void sse_encode_target_protocol(
    final TargetProtocol self,
    final SseSerializer serializer,
  );

  @protected
  void sse_encode_target_report(
    final TargetReport self,
    final SseSerializer serializer,
  );

  @protected
  void sse_encode_u_16(final int self, final SseSerializer serializer);

  @protected
  void sse_encode_u_64(final BigInt self, final SseSerializer serializer);

  @protected
  void sse_encode_u_8(final int self, final SseSerializer serializer);

  @protected
  void sse_encode_unit(final void self, final SseSerializer serializer);

  @protected
  void sse_encode_usize(final BigInt self, final SseSerializer serializer);

  @protected
  void sse_encode_web_probe(
    final WebProbe self,
    final SseSerializer serializer,
  );
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(final ExternalLibrary lib);

  void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetworkReport(
    final int ptr,
  ) =>
          wasmModule
              .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetworkReport(
            ptr,
          );

  void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetworkReport(
    final int ptr,
  ) =>
          wasmModule
              .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetworkReport(
            ptr,
          );

  void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSecurityFlagsResult(
    final int ptr,
  ) =>
          wasmModule
              .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSecurityFlagsResult(
            ptr,
          );

  void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSecurityFlagsResult(
    final int ptr,
  ) =>
          wasmModule
              .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSecurityFlagsResult(
            ptr,
          );
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetworkReport(
    final int ptr,
  );

  external void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetworkReport(
    final int ptr,
  );

  external void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSecurityFlagsResult(
    final int ptr,
  );

  external void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSecurityFlagsResult(
    final int ptr,
  );
}
