// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../../frb_generated.dart';
import '../models/net_info.dart';

/// Checks for the presence of a captive portal.
Future<CaptivePortalStatus> checkForCaptivePortal({
  required final BigInt timeoutMs,
}) =>
    RustLib.instance.api
        .crateApiProbesCaptivePortalCheckForCaptivePortal(timeoutMs: timeoutMs);

/// Web implementation stub (WASM removed).
Future<CaptivePortalStatus> checkForCaptivePortalWebManual({
  required final BigInt timeoutMs,
}) =>
    RustLib.instance.api
        .crateApiProbesCaptivePortalCheckForCaptivePortalWebManual(
      timeoutMs: timeoutMs,
    );

/// Unified entry point for captive portal check (WASM removed).
Future<CaptivePortalStatus> checkForCaptivePortalWeb({
  required final BigInt timeoutMs,
}) =>
    RustLib.instance.api.crateApiProbesCaptivePortalCheckForCaptivePortalWeb(
      timeoutMs: timeoutMs,
    );
