// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../../frb_generated.dart';
import '../models/net_info.dart';

/// Inspects system network interfaces to detect connection type and potential security flags.
Future<(SecurityFlagsResult, ConnectionType)> detectSecurityAndNetworkType() =>
    RustLib.instance.api.crateApiProbesInterfaceDetectSecurityAndNetworkType();

/// Web implementation stub (WASM removed).
Future<(SecurityFlagsResult, ConnectionType)>
    detectSecurityAndNetworkTypeWeb() => RustLib.instance.api
        .crateApiProbesInterfaceDetectSecurityAndNetworkTypeWeb();
