// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../models/report.dart';
import '../models/target.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Performs a network check against a single, specified target.
Future<TargetReport> checkTarget({required NetworkTarget target}) =>
    RustLib.instance.api.crateApiProbesTargetCheckTarget(target: target);

/// Native implementation of network reachability checks.
class NativeProbe {
  const NativeProbe();

  Future<TargetReport> check({required NetworkTarget target}) =>
      RustLib.instance.api
          .crateApiProbesTargetNativeProbeCheck(that: this, target: target);

  @override
  int get hashCode => 0;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeProbe && runtimeType == other.runtimeType;
}

/// Web-specific implementation stub (WASM removed).
class WebProbe {
  const WebProbe();

  Future<TargetReport> check({required NetworkTarget target}) =>
      RustLib.instance.api
          .crateApiProbesTargetWebProbeCheck(that: this, target: target);

  @override
  int get hashCode => 0;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WebProbe && runtimeType == other.runtimeType;
}
