// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../models/report.dart';
import '../models/target.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `NativeProbe`, `WebProbe`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `check`, `check`

Future<TargetReport> checkTarget({required NetworkTarget target}) =>
    RustLib.instance.api.crateApiProbesTargetCheckTarget(target: target);
