// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../models/net_info.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<List<TraceHop>> traceRoute(
        {required String host,
        required int maxHops,
        required BigInt timeoutPerHopMs}) =>
    RustLib.instance.api.crateApiProbesTracerouteTraceRoute(
        host: host, maxHops: maxHops, timeoutPerHopMs: timeoutPerHopMs);
