// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models/config.dart';
import 'models/net_info.dart';
import 'models/report.dart';
import 'models/target.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `analyze_single_sample`, `collect_network_samples`, `compute_latency_stats`, `evaluate_network_quality`, `perform_dns_security_check`

/// The main entry point for running a comprehensive network check.
///
/// This function orchestrates the entire check process:
/// 1. Collects latency samples via [collect_network_samples].
/// 2. Computes [LatencyStats].
/// 3. Evaluates [ConnectionQuality].
/// 4. Detects interface security and type.
/// 5. Compiles a final [NetworkReport].
Future<NetworkReport> checkNetwork({required NetworkConfiguration config}) =>
    RustLib.instance.api.crateApiEngineCheckNetwork(config: config);
