// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models/config.dart';
import 'models/net_info.dart';
import 'models/report.dart';
import 'models/target.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `analyze_single_sample`, `collect_network_samples`, `compute_latency_stats`, `evaluate_network_quality`, `get_winner_target`, `perform_dns_security_check`

/// The main entry point for running a comprehensive network check.
///
/// This function orchestrates the various probes and analyses based on the provided configuration.
Future<NetworkReport> checkNetwork({required NetworkConfiguration config}) =>
    RustLib.instance.api.crateApiEngineCheckNetwork(config: config);
