// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `check_target_internal`

Future<(BigInt?, BigInt?, BigInt?, double?)> calculateJitter(
        {required Uint64List latencies}) =>
    RustLib.instance.api.crateApiEngineCalculateJitter(latencies: latencies);

Future<NetworkReport> checkNetwork({required NetwrokConfiguration config}) =>
    RustLib.instance.api.crateApiEngineCheckNetwork(config: config);
