// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `NetworkError`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`

class CaptivePortalStatus {
  final bool isCaptivePortal;
  final String? redirectUrl;

  const CaptivePortalStatus({required this.isCaptivePortal, this.redirectUrl});

  @override
  int get hashCode => isCaptivePortal.hashCode ^ redirectUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CaptivePortalStatus &&
          runtimeType == other.runtimeType &&
          isCaptivePortal == other.isCaptivePortal &&
          redirectUrl == other.redirectUrl;
}

enum CheckStrategy { race, consensus }

enum ConnectionQuality {
  excellent,
  great,
  good,
  moderate,
  poor,
  unstable,
  dead,
}

enum ConnectionType { wifi, cellular, ethernet, vpn, bluetooth, unknown }

class LocalDevice {
  final String ipAddress;
  final String? hostname;
  final String? macAddress;

  const LocalDevice({required this.ipAddress, this.hostname, this.macAddress});

  @override
  int get hashCode =>
      ipAddress.hashCode ^ hostname.hashCode ^ macAddress.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LocalDevice &&
          runtimeType == other.runtimeType &&
          ipAddress == other.ipAddress &&
          hostname == other.hostname &&
          macAddress == other.macAddress;
}

class NetworkMetadata {
  final bool isVpn;
  final String interfaceName;

  const NetworkMetadata({required this.isVpn, required this.interfaceName});

  @override
  int get hashCode => isVpn.hashCode ^ interfaceName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NetworkMetadata &&
          runtimeType == other.runtimeType &&
          isVpn == other.isVpn &&
          interfaceName == other.interfaceName;
}

class NetworkReport {
  final BigInt timestampMs;
  final NetworkStatus status;
  final ConnectionType connectionType;
  final NetworkMetadata metadata;
  final List<TargetReport> targetReports;

  const NetworkReport({
    required this.timestampMs,
    required this.status,
    required this.connectionType,
    required this.metadata,
    required this.targetReports,
  });

  @override
  int get hashCode =>
      timestampMs.hashCode ^
      status.hashCode ^
      connectionType.hashCode ^
      metadata.hashCode ^
      targetReports.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NetworkReport &&
          runtimeType == other.runtimeType &&
          timestampMs == other.timestampMs &&
          status == other.status &&
          connectionType == other.connectionType &&
          metadata == other.metadata &&
          targetReports == other.targetReports;
}

class NetworkStatus {
  final bool isConnected;
  final ConnectionQuality quality;
  final BigInt latencyMs;
  final String winnerTarget;
  final BigInt? minLatencyMs;
  final BigInt? maxLatencyMs;
  final BigInt? meanLatencyMs;
  final double? stdDevLatencyMs;

  const NetworkStatus({
    required this.isConnected,
    required this.quality,
    required this.latencyMs,
    required this.winnerTarget,
    this.minLatencyMs,
    this.maxLatencyMs,
    this.meanLatencyMs,
    this.stdDevLatencyMs,
  });

  @override
  int get hashCode =>
      isConnected.hashCode ^
      quality.hashCode ^
      latencyMs.hashCode ^
      winnerTarget.hashCode ^
      minLatencyMs.hashCode ^
      maxLatencyMs.hashCode ^
      meanLatencyMs.hashCode ^
      stdDevLatencyMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NetworkStatus &&
          runtimeType == other.runtimeType &&
          isConnected == other.isConnected &&
          quality == other.quality &&
          latencyMs == other.latencyMs &&
          winnerTarget == other.winnerTarget &&
          minLatencyMs == other.minLatencyMs &&
          maxLatencyMs == other.maxLatencyMs &&
          meanLatencyMs == other.meanLatencyMs &&
          stdDevLatencyMs == other.stdDevLatencyMs;
}

class NetworkTarget {
  final String label;
  final String host;
  final int port;
  final TargetProtocol protocol;
  final BigInt timeoutMs;
  final int priority;
  final bool isEssential;

  const NetworkTarget({
    required this.label,
    required this.host,
    required this.port,
    required this.protocol,
    required this.timeoutMs,
    required this.priority,
    required this.isEssential,
  });

  @override
  int get hashCode =>
      label.hashCode ^
      host.hashCode ^
      port.hashCode ^
      protocol.hashCode ^
      timeoutMs.hashCode ^
      priority.hashCode ^
      isEssential.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NetworkTarget &&
          runtimeType == other.runtimeType &&
          label == other.label &&
          host == other.host &&
          port == other.port &&
          protocol == other.protocol &&
          timeoutMs == other.timeoutMs &&
          priority == other.priority &&
          isEssential == other.isEssential;
}

class NetwrokConfiguration {
  final List<NetworkTarget> targets;
  final CheckStrategy checkStrategy;
  final QualityThresholds qualityThreshold;
  final BigInt checkIntervalMs;
  final bool blockRequestWhenPoor;
  final int numJitterSamples;
  final double jitterThresholdPercent;

  const NetwrokConfiguration({
    required this.targets,
    required this.checkStrategy,
    required this.qualityThreshold,
    required this.checkIntervalMs,
    required this.blockRequestWhenPoor,
    required this.numJitterSamples,
    required this.jitterThresholdPercent,
  });

  static Future<NetwrokConfiguration> default_() =>
      RustLib.instance.api.crateApiModelsNetwrokConfigurationDefault();

  @override
  int get hashCode =>
      targets.hashCode ^
      checkStrategy.hashCode ^
      qualityThreshold.hashCode ^
      checkIntervalMs.hashCode ^
      blockRequestWhenPoor.hashCode ^
      numJitterSamples.hashCode ^
      jitterThresholdPercent.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NetwrokConfiguration &&
          runtimeType == other.runtimeType &&
          targets == other.targets &&
          checkStrategy == other.checkStrategy &&
          qualityThreshold == other.qualityThreshold &&
          checkIntervalMs == other.checkIntervalMs &&
          blockRequestWhenPoor == other.blockRequestWhenPoor &&
          numJitterSamples == other.numJitterSamples &&
          jitterThresholdPercent == other.jitterThresholdPercent;
}

class QualityThresholds {
  final BigInt excellent;
  final BigInt great;
  final BigInt good;
  final BigInt moderate;
  final BigInt poor;

  const QualityThresholds({
    required this.excellent,
    required this.great,
    required this.good,
    required this.moderate,
    required this.poor,
  });

  static Future<QualityThresholds> default_() =>
      RustLib.instance.api.crateApiModelsQualityThresholdsDefault();

  @override
  int get hashCode =>
      excellent.hashCode ^
      great.hashCode ^
      good.hashCode ^
      moderate.hashCode ^
      poor.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QualityThresholds &&
          runtimeType == other.runtimeType &&
          excellent == other.excellent &&
          great == other.great &&
          good == other.good &&
          moderate == other.moderate &&
          poor == other.poor;
}

enum TargetProtocol { tcp, udp }

class TargetReport {
  final String label;
  final bool success;
  final BigInt? latencyMs;
  final String? error;
  final bool isEssential;

  const TargetReport({
    required this.label,
    required this.success,
    this.latencyMs,
    this.error,
    required this.isEssential,
  });

  @override
  int get hashCode =>
      label.hashCode ^
      success.hashCode ^
      latencyMs.hashCode ^
      error.hashCode ^
      isEssential.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TargetReport &&
          runtimeType == other.runtimeType &&
          label == other.label &&
          success == other.success &&
          latencyMs == other.latencyMs &&
          error == other.error &&
          isEssential == other.isEssential;
}

class TraceHop {
  final int hopNumber;
  final String ipAddress;
  final String? hostname;
  final BigInt? latencyMs;

  const TraceHop({
    required this.hopNumber,
    required this.ipAddress,
    this.hostname,
    this.latencyMs,
  });

  @override
  int get hashCode =>
      hopNumber.hashCode ^
      ipAddress.hashCode ^
      hostname.hashCode ^
      latencyMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TraceHop &&
          runtimeType == other.runtimeType &&
          hopNumber == other.hopNumber &&
          ipAddress == other.ipAddress &&
          hostname == other.hostname &&
          latencyMs == other.latencyMs;
}
