// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: public_member_api_docs, invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'target.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// Defines the strategy used when evaluating multiple network targets.
///
/// This strategy determines how the engine decides if the network is "up"
/// when multiple targets are configured.
enum CheckStrategy {
  /// The first target to respond successfully determines the result.
  ///
  /// This is the fastest strategy as it doesn't wait for other targets.
  /// It's ideal for performance-sensitive applications where any connectivity
  /// to a trusted endpoint is sufficient.
  race,

  /// A majority of targets must respond successfully for the check to be
  /// considered a success.
  ///
  /// This strategy is more robust against localized outages or transient
  /// failures of individual endpoints. It is slower than [Race] because
  /// it may wait for multiple responses.
  consensus,
  ;
}

/// Represents the perceived quality of the network connection based on latency and stability.
enum ConnectionQuality {
  /// Excellent connection with very low latency.
  ///
  /// Typically < 50ms. Suitable for high-performance real-time tasks like
  /// competitive gaming or high-frequency trading.
  excellent,

  /// Great connection with low latency.
  ///
  /// Typically < 100ms. Suitable for VoIP, video conferencing, and smooth browsing.
  great,

  /// Good, usable connection with acceptable latency.
  ///
  /// Typically < 150ms. Suitable for most standard web applications and streaming.
  good,

  /// Moderate connection with noticeable latency.
  ///
  /// Typically < 250ms. Users might notice slight delays in interactive elements.
  moderate,

  /// Poor connection with high latency.
  ///
  /// Typically < 500ms. Basic browsing will feel slow, and real-time apps will struggle.
  poor,

  /// Connection is active, but high jitter or packet loss makes it unreliable.
  ///
  /// The network is "connected" but the experience will be degraded and unpredictable.
  unstable,

  /// A captive portal (login page) was detected.
  ///
  /// The device is connected to an AP, but internet access is restricted until
  /// the user interacts with the portal (e.g., at an airport or hotel).
  captivePortal,

  /// No connection detected or all essential targets failed.
  ///
  /// The network is completely unreachable or unusable.
  offline,
  ;
}

/// The main configuration object for the network reachability engine.
///
/// This struct aggregates all settings including targets, intervals,
/// quality thresholds, and security/resilience preferences.
class NetworkConfiguration {
  /// A list of network endpoints ([NetworkTarget]) to be monitored.
  final List<NetworkTarget> targets;

  /// The interval in milliseconds between automatic periodic checks.
  ///
  /// Set to 0 to disable periodic background checks and rely on manual triggers.
  final BigInt checkIntervalMs;

  /// The duration (in milliseconds) for which a network report is cached.
  ///
  /// Rapid consecutive calls will return the cached report to save battery and bandwidth.
  final BigInt cacheValidityMs;

  /// Custom latency thresholds for determining connection quality.
  final QualityThresholds qualityThreshold;

  /// Security-specific settings such as VPN and DNS hijacking detection.
  final SecurityConfig security;

  /// Resilience settings including circuit breakers and jitter analysis.
  final ResilienceConfig resilience;

  const NetworkConfiguration({
    required this.targets,
    required this.checkIntervalMs,
    required this.cacheValidityMs,
    required this.qualityThreshold,
    required this.security,
    required this.resilience,
  });

  /// Creates a production-ready default configuration.
  ///
  /// The default setup includes:
  /// - Monitoring multiple high-availability targets (Cloudflare and Google).
  /// - Automatic periodic checks every 5 seconds.
  /// - 2-second result caching to prevent redundant probes.
  static Future<NetworkConfiguration> default_() =>
      RustLib.instance.api.crateApiModelsConfigNetworkConfigurationDefault();

  @override
  int get hashCode =>
      targets.hashCode ^
      checkIntervalMs.hashCode ^
      cacheValidityMs.hashCode ^
      qualityThreshold.hashCode ^
      security.hashCode ^
      resilience.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NetworkConfiguration &&
          runtimeType == other.runtimeType &&
          targets == other.targets &&
          checkIntervalMs == other.checkIntervalMs &&
          cacheValidityMs == other.cacheValidityMs &&
          qualityThreshold == other.qualityThreshold &&
          security == other.security &&
          resilience == other.resilience;
}

/// Defines the latency thresholds (in milliseconds) used to determine [ConnectionQuality].
///
/// These values allow customizing what "Good" or "Poor" means for your specific application.
class QualityThresholds {
  /// Latency at or below this value is considered [ConnectionQuality::Excellent].
  final BigInt excellent;

  /// Latency at or below this value is considered [ConnectionQuality::Great].
  final BigInt great;

  /// Latency at or below this value is considered [ConnectionQuality::Good].
  final BigInt good;

  /// Latency at or below this value is considered [ConnectionQuality::Moderate].
  final BigInt moderate;

  /// Latency at or below this value is considered [ConnectionQuality::Poor].
  /// Anything higher is categorized as [ConnectionQuality::Unstable] or [ConnectionQuality::Poor].
  final BigInt poor;

  const QualityThresholds({
    required this.excellent,
    required this.great,
    required this.good,
    required this.moderate,
    required this.poor,
  });

  /// Provides sensible default latency thresholds for most mobile and web applications.
  ///
  /// Defaults:
  /// - Excellent: 50ms
  /// - Great: 100ms
  /// - Good: 150ms
  /// - Moderate: 250ms
  /// - Poor: 500ms
  static Future<QualityThresholds> default_() =>
      RustLib.instance.api.crateApiModelsConfigQualityThresholdsDefault();

  @override
  int get hashCode =>
      excellent.hashCode ^
      great.hashCode ^
      good.hashCode ^
      moderate.hashCode ^
      poor.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QualityThresholds &&
          runtimeType == other.runtimeType &&
          excellent == other.excellent &&
          great == other.great &&
          good == other.good &&
          moderate == other.moderate &&
          poor == other.poor;
}

/// Configuration for resilience, stability analysis, and performance tuning.
class ResilienceConfig {
  /// The evaluation strategy to use when checking multiple targets.
  final CheckStrategy strategy;

  /// The number of consecutive failures of essential targets before the
  /// circuit breaker opens.
  ///
  /// A value of 0 disables the circuit breaker mechanism.
  final int circuitBreakerThreshold;

  /// The cooldown period in milliseconds.
  ///
  /// After this time, the circuit breaker transitions from 'Open' to 'Half-Open',
  /// allowing a trial check to see if the network has recovered.
  final BigInt circuitBreakerCooldownMs;

  /// Number of samples to take for jitter and stability analysis.
  ///
  /// Higher values provide more accurate stability metrics but increase check duration.
  /// Must be > 1 to enable jitter calculation.
  final int numJitterSamples;

  /// The percentage of mean latency that the standard deviation must exceed
  /// to be flagged as high jitter.
  ///
  /// High jitter can downgrade the perceived [ConnectionQuality] to [ConnectionQuality::Unstable].
  final double jitterThresholdPercent;

  /// The minimum stability score (0-100) required to avoid the 'Unstable' quality tag.
  final int stabilityThershold;

  /// The packet loss percentage above which the connection is marked as [ConnectionQuality::Unstable].
  final double criticalPacketLossPrecent;

  const ResilienceConfig({
    required this.strategy,
    required this.circuitBreakerThreshold,
    required this.circuitBreakerCooldownMs,
    required this.numJitterSamples,
    required this.jitterThresholdPercent,
    required this.stabilityThershold,
    required this.criticalPacketLossPrecent,
  });

  /// Provides a standard resilience configuration balanced for stability and speed.
  ///
  /// Defaults:
  /// - Strategy: [CheckStrategy::Race]
  /// - Circuit Breaker: Disabled (threshold 0)
  /// - Cooldown: 1 minute
  /// - Jitter Samples: 5
  /// - Stability Threshold: 80
  static Future<ResilienceConfig> default_() =>
      RustLib.instance.api.crateApiModelsConfigResilienceConfigDefault();

  @override
  int get hashCode =>
      strategy.hashCode ^
      circuitBreakerThreshold.hashCode ^
      circuitBreakerCooldownMs.hashCode ^
      numJitterSamples.hashCode ^
      jitterThresholdPercent.hashCode ^
      stabilityThershold.hashCode ^
      criticalPacketLossPrecent.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ResilienceConfig &&
          runtimeType == other.runtimeType &&
          strategy == other.strategy &&
          circuitBreakerThreshold == other.circuitBreakerThreshold &&
          circuitBreakerCooldownMs == other.circuitBreakerCooldownMs &&
          numJitterSamples == other.numJitterSamples &&
          jitterThresholdPercent == other.jitterThresholdPercent &&
          stabilityThershold == other.stabilityThershold &&
          criticalPacketLossPrecent == other.criticalPacketLossPrecent;
}

/// Configuration for security-related network checks.
class SecurityConfig {
  /// If true, the reachability engine will flag or block connections if a VPN is detected.
  ///
  /// This is useful for region-locked content or compliance requirements.
  final bool blockVpn;

  /// If true, performs a check to detect potential DNS hijacking.
  ///
  /// This involves comparing results from the system DNS with a trusted resolver.
  /// Note: This adds a small amount of latency to each check.
  final bool detectDnsHijack;

  const SecurityConfig({
    required this.blockVpn,
    required this.detectDnsHijack,
  });

  static Future<SecurityConfig> default_() =>
      RustLib.instance.api.crateApiModelsConfigSecurityConfigDefault();

  @override
  int get hashCode => blockVpn.hashCode ^ detectDnsHijack.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SecurityConfig &&
          runtimeType == other.runtimeType &&
          blockVpn == other.blockVpn &&
          detectDnsHijack == other.detectDnsHijack;
}
