// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`

/// The result of a captive portal check.
class CaptivePortalStatus {
  /// True if a captive portal was detected (i.e., the probe was redirected).
  final bool isCaptivePortal;

  /// The URL that the probe was redirected to, if a portal was detected.
  final String? redirectUrl;

  /// The result of a captive portal check.

  const CaptivePortalStatus({
    required this.isCaptivePortal,
    this.redirectUrl,
  });

  @override
  int get hashCode => isCaptivePortal.hashCode ^ redirectUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CaptivePortalStatus &&
          runtimeType == other.runtimeType &&
          isCaptivePortal == other.isCaptivePortal &&
          redirectUrl == other.redirectUrl;
}

/// Represents the type of physical or logical network connection.
enum ConnectionType {
  /// A WiFi connection.
  wifi,

  /// A mobile data connection (e.g., LTE, 5G).
  cellular,

  /// A wired Ethernet connection.
  ethernet,

  /// A Virtual Private Network connection.
  vpn,

  /// A Bluetooth tethering connection.
  bluetooth,

  /// The connection type could not be determined.
  unknown,
  ;
}

/// A report of security-related attributes of the current network connection.
class SecurityFlags {
  /// True if the active interface is a known VPN/tunnel type (e.g., 'tun', 'ppp').
  final bool isVpnDetected;

  /// True if a DNS mismatch was found between system and trusted resolvers,
  /// indicating a potential DNS hijacking or spoofing attack.
  final bool isDnsSpoofed;

  /// True if a system-level proxy is detected (future implementation).
  final bool isProxyDetected;

  /// The name of the active network interface (e.g., 'wlan0', 'tun0').
  final String interfaceName;

  /// A report of security-related attributes of the current network connection.

  const SecurityFlags({
    required this.isVpnDetected,
    required this.isDnsSpoofed,
    required this.isProxyDetected,
    required this.interfaceName,
  });

  /// The default value
  static Future<SecurityFlags> default_() =>
      RustLib.instance.api.crateApiModelsNetInfoSecurityFlagsDefault();

  @override
  int get hashCode =>
      isVpnDetected.hashCode ^
      isDnsSpoofed.hashCode ^
      isProxyDetected.hashCode ^
      interfaceName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SecurityFlags &&
          runtimeType == other.runtimeType &&
          isVpnDetected == other.isVpnDetected &&
          isDnsSpoofed == other.isDnsSpoofed &&
          isProxyDetected == other.isProxyDetected &&
          interfaceName == other.interfaceName;
}

/// Represents a single hop in a traceroute path.
class TraceHop {
  /// The hop number in the sequence (Time-To-Live value).
  final int hopNumber;

  /// The IP address of the router at this hop. Can be "*" if the hop timed out.
  final String ipAddress;

  /// The hostname resolved from the IP address, if available.
  final String? hostname;

  /// The round-trip time to this hop in milliseconds.
  final BigInt? latencyMs;

  /// Represents a single hop in a traceroute path.

  const TraceHop({
    required this.hopNumber,
    required this.ipAddress,
    this.hostname,
    this.latencyMs,
  });

  @override
  int get hashCode =>
      hopNumber.hashCode ^
      ipAddress.hashCode ^
      hostname.hashCode ^
      latencyMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TraceHop &&
          runtimeType == other.runtimeType &&
          hopNumber == other.hopNumber &&
          ipAddress == other.ipAddress &&
          hostname == other.hostname &&
          latencyMs == other.latencyMs;
}
