// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `TraceHop`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SecurityFlagsResult>>
abstract class SecurityFlagsResult implements RustOpaqueInterface {
  String get interfaceName;

  bool get isDnsSpoofed;

  bool get isProxyDetected;

  bool get isVpnDetected;

  set interfaceName(String interfaceName);

  set isDnsSpoofed(bool isDnsSpoofed);

  set isProxyDetected(bool isProxyDetected);

  set isVpnDetected(bool isVpnDetected);

  static Future<SecurityFlagsResult> default_() =>
      RustLib.instance.api.crateApiModelsNetInfoSecurityFlagsResultDefault();
}

/// The result of a captive portal check.
class CaptivePortalStatus {
  /// True if a captive portal was detected (i.e., the probe was redirected).
  final bool isCaptivePortal;

  /// The URL that the probe was redirected to, if a portal was detected.
  final String? redirectUrl;

  const CaptivePortalStatus({
    required this.isCaptivePortal,
    this.redirectUrl,
  });

  @override
  int get hashCode => isCaptivePortal.hashCode ^ redirectUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CaptivePortalStatus &&
          runtimeType == other.runtimeType &&
          isCaptivePortal == other.isCaptivePortal &&
          redirectUrl == other.redirectUrl;
}

/// Represents the type of physical or logical network connection.
enum ConnectionType {
  /// A WiFi connection.
  wifi,

  /// A mobile data connection (e.g., LTE, 5G).
  cellular,

  /// A wired Ethernet connection.
  ethernet,

  /// A Virtual Private Network connection.
  vpn,

  /// A Bluetooth tethering connection.
  bluetooth,

  /// A Loopback
  loopback,

  /// The connection type could not be determined.
  unknown,
  ;

  static Future<ConnectionType> default_() =>
      RustLib.instance.api.crateApiModelsNetInfoConnectionTypeDefault();
}

/// A report of security-related attributes of the current network connection.
class SecurityFlags {
  /// True if the active interface is a known VPN/tunnel type (e.g., 'tun', 'ppp').
  final bool isVpnDetected;

  /// True if a DNS mismatch was found between system and trusted resolvers,
  /// indicating a potential DNS hijacking or spoofing attack.
  final bool isDnsSpoofed;

  /// True if a system-level proxy is detected (future implementation).
  final bool isProxyDetected;

  /// The name of the active network interface (e.g., 'wlan0', 'tun0').
  final String interfaceName;

  const SecurityFlags({
    required this.isVpnDetected,
    required this.isDnsSpoofed,
    required this.isProxyDetected,
    required this.interfaceName,
  });

  static Future<SecurityFlags> default_() =>
      RustLib.instance.api.crateApiModelsNetInfoSecurityFlagsDefault();

  @override
  int get hashCode =>
      isVpnDetected.hashCode ^
      isDnsSpoofed.hashCode ^
      isProxyDetected.hashCode ^
      interfaceName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SecurityFlags &&
          runtimeType == other.runtimeType &&
          isVpnDetected == other.isVpnDetected &&
          isDnsSpoofed == other.isDnsSpoofed &&
          isProxyDetected == other.isProxyDetected &&
          interfaceName == other.interfaceName;
}
