// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `eq`, `fmt`, `fmt`

/// Configuration for a specific network endpoint to be monitored.
class NetworkTarget {
  /// A human-readable identifier for the target (e.g., "Primary DNS", "API Gateway").
  final String label;

  /// The remote address to check. Can be a domain name (google.com) or an IP address (8.8.8.8).
  final String host;

  /// The destination port for the check (e.g., 80 for HTTP, 443 for HTTPS, 53 for DNS).
  final int port;

  /// The network protocol to use for the probe.
  final TargetProtocol protocol;

  /// The maximum time in milliseconds to wait for a response before timing out.
  final BigInt timeoutMs;

  /// The relative priority of this target (lower numbers = higher priority).
  ///
  /// While the current engine treats all targets equally, this field is useful
  /// for UI sorting or selective checking in future versions.
  final int priority;

  /// If true, a failure of this specific target is considered a critical event.
  ///
  /// Essential targets trigger the circuit breaker and can disqualify
  /// the network from being considered "connected" depending on the strategy.
  final bool isEssential;

  const NetworkTarget({
    required this.label,
    required this.host,
    required this.port,
    required this.protocol,
    required this.timeoutMs,
    required this.priority,
    required this.isEssential,
  });

  @override
  int get hashCode =>
      label.hashCode ^
      host.hashCode ^
      port.hashCode ^
      protocol.hashCode ^
      timeoutMs.hashCode ^
      priority.hashCode ^
      isEssential.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NetworkTarget &&
          runtimeType == other.runtimeType &&
          label == other.label &&
          host == other.host &&
          port == other.port &&
          protocol == other.protocol &&
          timeoutMs == other.timeoutMs &&
          priority == other.priority &&
          isEssential == other.isEssential;
}

/// Supported protocols for network reachability checks.
enum TargetProtocol {
  /// Transmission Control Protocol.
  ///
  /// Performs a full 3-way handshake to ensure the port is open and accepting connections.
  tcp,

  /// Internet Control Message Protocol.
  ///
  /// Sends an Echo Request (ping). Requires appropriate OS permissions.
  icmp,

  /// Hypertext Transfer Protocol.
  ///
  /// Performs a GET or HEAD request and expects a successful status code (2xx/3xx).
  http,

  /// Secure Hypertext Transfer Protocol.
  ///
  /// Performs an encrypted request over TLS. Validates the certificate chain by default.
  https,
  ;
}
