// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `eq`, `fmt`, `fmt`

class NetworkTarget {
  final String label;
  final String host;
  final int port;
  final TargetProtocol protocol;
  final BigInt timeoutMs;
  final int priority;
  final bool isEssential;

  const NetworkTarget({
    required this.label,
    required this.host,
    required this.port,
    required this.protocol,
    required this.timeoutMs,
    required this.priority,
    required this.isEssential,
  });

  @override
  int get hashCode =>
      label.hashCode ^
      host.hashCode ^
      port.hashCode ^
      protocol.hashCode ^
      timeoutMs.hashCode ^
      priority.hashCode ^
      isEssential.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NetworkTarget &&
          runtimeType == other.runtimeType &&
          label == other.label &&
          host == other.host &&
          port == other.port &&
          protocol == other.protocol &&
          timeoutMs == other.timeoutMs &&
          priority == other.priority &&
          isEssential == other.isEssential;
}

enum TargetProtocol {
  tcp,
  udp,
  ;
}
