// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `eq`, `fmt`, `fmt`

/// Defines a single network endpoint to be checked.
class NetworkTarget {
  /// A unique, human-readable label for this target (e.g., "Google DNS").
  final String label;

  /// The hostname or IP address of the target.
  final String host;

  /// The port number to connect to.
  final int port;

  /// The protocol (TCP or UDP) to use for the check.
  final TargetProtocol protocol;

  /// The timeout in milliseconds for this specific target check.
  final BigInt timeoutMs;

  /// The priority of the target. While not used in the current engine logic,
  /// it can be used by the caller for sorting or selection. (e.g., 1=High).
  final int priority;

  /// If true, a failure to connect to this target will be considered a critical
  /// failure, affecting the circuit breaker and potentially the overall check status.
  final bool isEssential;

  /// Defines a single network endpoint to be checked.

  const NetworkTarget({
    required this.label,
    required this.host,
    required this.port,
    required this.protocol,
    required this.timeoutMs,
    required this.priority,
    required this.isEssential,
  });

  @override
  int get hashCode =>
      label.hashCode ^
      host.hashCode ^
      port.hashCode ^
      protocol.hashCode ^
      timeoutMs.hashCode ^
      priority.hashCode ^
      isEssential.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NetworkTarget &&
          runtimeType == other.runtimeType &&
          label == other.label &&
          host == other.host &&
          port == other.port &&
          protocol == other.protocol &&
          timeoutMs == other.timeoutMs &&
          priority == other.priority &&
          isEssential == other.isEssential;
}

/// The network protocol to use for a check.
enum TargetProtocol {
  /// Use the Transmission Control Protocol (TCP). This is a reliable, connection-oriented protocol.
  tcp,

  /// Use the User Datagram Protocol (UDP). This is a fast, connectionless protocol.
  udp,
  ;
}
