// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../../frb_generated.dart';
import '../models/config.dart';
import '../models/report.dart';
import '../models/target.dart';

/// Categorizes a single latency measurement against configured thresholds.
///
/// This is a simple threshold-based classifier used for individual probes.
///
/// # Arguments
///
/// * `latency` - Measured round-trip time in milliseconds.
/// * `threshold` - The [QualityThresholds] defining the boundaries for each category.
///
/// # Returns
///
/// A [ConnectionQuality] variant. If latency exceeds the `poor` threshold,
/// it returns [ConnectionQuality::Offline].
Future<ConnectionQuality> evaluateQuality(
        {required BigInt latency, required QualityThresholds threshold}) =>
    RustLib.instance.api.crateApiAnalysisQualityEvaluateQuality(
        latency: latency, threshold: threshold);

/// Computes the final, consolidated network quality.
///
/// Unlike [evaluate_quality], this function considers the "Big Three" of networking:
/// 1. **Speed:** Absolute latency.
/// 2. **Reliability:** Packet loss percentage.
/// 3. **Consistency:** Stability score (derived from jitter and variance).
///
/// # Logic Flow
///
/// * If not connected, returns `Offline`.
/// * If packet loss exceeds the critical threshold, returns `Unstable`.
/// * If stability is low, the quality is downgraded by one or more levels.
/// * Otherwise, the quality is primarily determined by speed (latency).
Future<ConnectionQuality> evaluateNetworkQuality(
        {required bool isConnected,
        required LatencyStats stats,
        required NetworkConfiguration config}) =>
    RustLib.instance.api.crateApiAnalysisQualityEvaluateNetworkQuality(
        isConnected: isConnected, stats: stats, config: config);
