// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../../frb_generated.dart';
import '../models/config.dart';
import '../models/report.dart';

// These functions are ignored because they are not marked as `pub`: `lerp`

/// Calculates basic statistical metrics for a set of latency samples.
///
/// Useful for quick analysis of a probe cycle.
///
/// # Returns
///
/// A tuple: `(Min, Max, Mean, StandardDeviation)`.
Future<(BigInt?, BigInt?, BigInt?, double?)> calculateJitterStats(
        {required Uint64List latencies}) =>
    RustLib.instance.api
        .crateApiAnalysisStatsCalculateJitterStats(latencies: latencies);

/// Computes a comprehensive stability report and health score.
///
/// The scoring system is specifically tuned for modern mobile (4G/5G) and
/// WiFi networks. It uses a weighted composite model:
///
/// ### Scoring Weights:
/// * **P95 Latency (35%):** Penalizes "tail latency" (occasional slow packets).
/// * **Packet Loss (30%):** Heavily penalizes unreliability.
/// * **Mean Latency (20%):** Baseline speed assessment.
/// * **IQR Jitter (15%):** Measures arrival consistency using Interquartile Range.
///
/// # Arguments
/// * `latencies`: Successful probe results.
/// * `total_expected_samples`: Used to calculate packet loss.
/// * `thresholds`: User-defined latency boundaries.
Future<LatencyStats> computeLatencyStats(
        {required Uint64List latencies,
        required int totalExpectedSamples,
        required QualityThresholds thresholds}) =>
    RustLib.instance.api.crateApiAnalysisStatsComputeLatencyStats(
        latencies: latencies,
        totalExpectedSamples: totalExpectedSamples,
        thresholds: thresholds);
