// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../models/net_info.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Checks for the presence of a captive portal.
Future<CaptivePortalStatus> checkForCaptivePortal(
        {required BigInt timeoutMs}) =>
    RustLib.instance.api
        .crateApiProbesCaptivePortalCheckForCaptivePortal(timeoutMs: timeoutMs);

/// Web implementation using Fetch with redirect: manual.
Future<CaptivePortalStatus> checkForCaptivePortalWebManual(
        {required BigInt timeoutMs}) =>
    RustLib.instance.api
        .crateApiProbesCaptivePortalCheckForCaptivePortalWebManual(
            timeoutMs: timeoutMs);

/// Unified entry point for captive portal check.
Future<CaptivePortalStatus> checkForCaptivePortalWeb(
        {required BigInt timeoutMs}) =>
    RustLib.instance.api.crateApiProbesCaptivePortalCheckForCaptivePortalWeb(
        timeoutMs: timeoutMs);
