// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: public_member_api_docs, invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'target.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// Defines the strategy used when evaluating multiple network targets during a check cycle.
///
/// When the engine is configured with multiple targets, the `CheckStrategy` determines
/// the logic for deciding the overall "connected" status of the network.
enum CheckStrategy {
  /// The first target to respond successfully determines the result.
  ///
  /// # Behavior
  /// In this mode, the engine initiates checks for all configured targets concurrently.
  /// As soon as a single target returns a successful response, the network is marked
  /// as "connected" and the engine returns the result immediately.
  ///
  /// # Use Case
  /// This is the fastest strategy and is ideal for performance-sensitive applications
  /// where knowing *any* path to the internet is open is sufficient. It minimizes
  /// latency for the check itself.
  race,

  /// A majority of targets must respond successfully for the check to be considered a success.
  ///
  /// # Behavior
  /// The engine waits for a quorum of targets to respond. For example, if 3 targets
  /// are configured, at least 2 must succeed for the overall status to be "connected".
  /// If the majority fails, the network is considered "offline" or "unstable".
  ///
  /// # Use Case
  /// This strategy provides high robustness against transient failures of specific
  /// servers (e.g., a specific DNS provider being down). It's best for critical
  /// applications that require high confidence in the network's reliability.
  consensus,
  ;
}

/// Represents the perceived quality of the network connection based on latency, jitter, and stability.
///
/// The engine maps raw metrics (like RTT in milliseconds) to these categories using
/// the thresholds defined in [`QualityThresholds`].
enum ConnectionQuality {
  /// Excellent connection with very low latency and high stability.
  ///
  /// Typically < 50ms.
  /// **User Experience:** Instantaneous page loads, seamless 4K streaming, and
  /// zero-lag competitive gaming.
  excellent,

  /// Great connection with low latency.
  ///
  /// Typically < 100ms.
  /// **User Experience:** Fast browsing, high-quality video calls (VoIP/Zoom)
  /// without noticeable delay.
  great,

  /// Good, usable connection with acceptable latency.
  ///
  /// Typically < 150ms.
  /// **User Experience:** Reliable for most tasks, though large file uploads
  /// or fast-paced games might show slight degradation.
  good,

  /// Moderate connection with noticeable latency.
  ///
  /// Typically < 250ms.
  /// **User Experience:** Noticeable delays when opening new pages. Video streaming
  /// might occasionally buffer at the start.
  moderate,

  /// Poor connection with high latency.
  ///
  /// Typically < 500ms.
  /// **User Experience:** Frustratingly slow. Interactive applications feel
  /// "heavy" and unresponsive.
  poor,

  /// Connection is active, but high jitter or packet loss makes it unreliable.
  ///
  /// This state occurs when latency is technically okay, but the "consistency"
  /// is missing (e.g., standard deviation of samples is too high).
  /// **User Experience:** "Stuttering" in calls, frequent disconnects,
  /// and unpredictable performance.
  unstable,

  /// A captive portal (login page) was detected.
  ///
  /// The device is connected to a WiFi access point, but internet access is
  /// intercepted by a gateway (common in hotels/airports).
  /// **User Experience:** No internet access until the user signs in or
  /// accepts terms.
  captivePortal,

  /// No connection detected or all essential targets failed.
  ///
  /// **User Experience:** The app should enter its "Offline Mode".
  offline,
  ;
}

/// The master configuration for the Network Reachability Engine.
///
/// This structure is the entry point for customizing how the engine behaves.
/// It should be initialized once and passed to the engine during startup.
class NetworkConfiguration {
  /// The list of endpoints ([`NetworkTarget` models](super::target::NetworkTarget))
  /// to probe.
  final List<NetworkTarget> targets;

  /// Frequency (ms) of background checks.
  ///
  /// If set to 5000, the engine will automatically run a check every 5 seconds
  /// and stream results. Set to 0 to disable periodic checks.
  final BigInt checkIntervalMs;

  /// Cache duration (ms) for results.
  ///
  /// If a manual check is requested within this window of a previous check,
  /// the engine will return the cached result instead of performing new
  /// network I/O. This saves significant battery and data.
  final BigInt cacheValidityMs;

  /// Thresholds for quality categorization.
  final QualityThresholds qualityThreshold;

  /// Security policy settings.
  final SecurityConfig security;

  /// Performance and resilience settings.
  final ResilienceConfig resilience;

  const NetworkConfiguration({
    required this.targets,
    required this.checkIntervalMs,
    required this.cacheValidityMs,
    required this.qualityThreshold,
    required this.security,
    required this.resilience,
  });

  /// Standard production-ready configuration.
  ///
  /// Includes:
  /// - **Targets:** Cloudflare (HTTP/HTTPS/TCP/ICMP) and Google (TCP/ICMP).
  /// - **Interval:** 5 seconds.
  /// - **Cache:** 2 seconds.
  /// - **Defaults:** Balanced quality and resilience settings.
  static Future<NetworkConfiguration> default_() =>
      RustLib.instance.api.crateApiModelsConfigNetworkConfigurationDefault();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  /// Constructs a full [`NetworkConfiguration`].
  static Future<NetworkConfiguration> newInstance(
          {required List<NetworkTarget> targets,
          required BigInt checkIntervalMs,
          required BigInt cacheValidityMs,
          required QualityThresholds qualityThreshold,
          required SecurityConfig security,
          required ResilienceConfig resilience}) =>
      RustLib.instance.api.crateApiModelsConfigNetworkConfigurationNew(
          targets: targets,
          checkIntervalMs: checkIntervalMs,
          cacheValidityMs: cacheValidityMs,
          qualityThreshold: qualityThreshold,
          security: security,
          resilience: resilience);

  @override
  int get hashCode =>
      targets.hashCode ^
      checkIntervalMs.hashCode ^
      cacheValidityMs.hashCode ^
      qualityThreshold.hashCode ^
      security.hashCode ^
      resilience.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NetworkConfiguration &&
          runtimeType == other.runtimeType &&
          targets == other.targets &&
          checkIntervalMs == other.checkIntervalMs &&
          cacheValidityMs == other.cacheValidityMs &&
          qualityThreshold == other.qualityThreshold &&
          security == other.security &&
          resilience == other.resilience;
}

/// Defines the latency thresholds (in milliseconds) used to categorize [`ConnectionQuality`].
///
/// These values act as the "buckets" that convert raw Round-Trip Time (RTT) values
/// into user-friendly quality ratings.
class QualityThresholds {
  /// Maximum latency (ms) to be considered [`ConnectionQuality::Excellent`].
  /// *Default: 50ms*
  final BigInt excellent;

  /// Maximum latency (ms) to be considered [`ConnectionQuality::Great`].
  /// *Default: 100ms*
  final BigInt great;

  /// Maximum latency (ms) to be considered [`ConnectionQuality::Good`].
  /// *Default: 150ms*
  final BigInt good;

  /// Maximum latency (ms) to be considered [`ConnectionQuality::Moderate`].
  /// *Default: 250ms*
  final BigInt moderate;

  /// Maximum latency (ms) to be considered [`ConnectionQuality::Poor`].
  /// Anything above this is typically marked as [`ConnectionQuality::Poor`] or
  /// [`ConnectionQuality::Unstable`].
  /// *Default: 500ms*
  final BigInt poor;

  const QualityThresholds({
    required this.excellent,
    required this.great,
    required this.good,
    required this.moderate,
    required this.poor,
  });

  /// Provides industry-standard default latency thresholds for most applications.
  ///
  /// These defaults are tuned for general-purpose mobile and web apps:
  /// - **Excellent:** 50ms (Fiber/High-speed Cable)
  /// - **Great:** 100ms (Average Broadband)
  /// - **Good:** 150ms (Stable 4G/LTE)
  /// - **Moderate:** 250ms (3G/Slower Satellite)
  /// - **Poor:** 500ms (Highly congested or edge networks)
  static Future<QualityThresholds> default_() =>
      RustLib.instance.api.crateApiModelsConfigQualityThresholdsDefault();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  /// Creates a new custom [`QualityThresholds`] instance.
  ///
  /// # Arguments
  /// * `excellent` - Threshold for 'Excellent' (ms).
  /// * `great` - Threshold for 'Great' (ms).
  /// * `good` - Threshold for 'Good' (ms).
  /// * `moderate` - Threshold for 'Moderate' (ms).
  /// * `poor` - Threshold for 'Poor' (ms).
  static Future<QualityThresholds> newInstance(
          {required BigInt excellent,
          required BigInt great,
          required BigInt good,
          required BigInt moderate,
          required BigInt poor}) =>
      RustLib.instance.api.crateApiModelsConfigQualityThresholdsNew(
          excellent: excellent,
          great: great,
          good: good,
          moderate: moderate,
          poor: poor);

  @override
  int get hashCode =>
      excellent.hashCode ^
      great.hashCode ^
      good.hashCode ^
      moderate.hashCode ^
      poor.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QualityThresholds &&
          runtimeType == other.runtimeType &&
          excellent == other.excellent &&
          great == other.great &&
          good == other.good &&
          moderate == other.moderate &&
          poor == other.poor;
}

/// Configuration for network resilience, failure handling, and statistical analysis.
///
/// This struct controls the "brain" of the engine: how it handles noise,
/// how it reacts to failure, and how it calculates jitter.
class ResilienceConfig {
  /// The evaluation strategy (Race vs Consensus) for multi-target checks.
  final CheckStrategy strategy;

  /// Number of consecutive failures before the "Circuit Breaker" opens.
  ///
  /// When the circuit breaker is 'Open', the engine stops sending probes to
  /// save resources and battery, assuming the network is definitely down.
  /// *Set to 0 to disable.*
  final int circuitBreakerThreshold;

  /// Duration (ms) the engine waits before attempting a "Half-Open" probe.
  ///
  /// Once the circuit breaker is open, it waits for this cooldown before
  /// trying one more check to see if connectivity has returned.
  final BigInt circuitBreakerCooldownMs;

  /// Number of packets/samples to send per target for statistical analysis.
  ///
  /// Higher values (e.g., 10+) provide extremely accurate jitter and packet loss
  /// metrics but increase the battery/data usage and duration of each check.
  /// *Minimum 2 required for jitter calculation.*
  final int numJitterSamples;

  /// Percentage threshold for jitter classification.
  ///
  /// If the standard deviation of latency samples divided by the mean exceeds
  /// this percentage, the connection is marked as 'Unstable'.
  final double jitterThresholdPercent;

  /// Minimum stability score (0-100) required for a 'Stable' rating.
  ///
  /// A score calculated from packet loss and jitter consistency.
  final int stabilityThershold;

  /// Critical packet loss percentage (0.0 - 100.0).
  ///
  /// If packet loss exceeds this value, the connection is immediately
  /// downgraded to 'Unstable' or 'Offline'.
  final double criticalPacketLossPrecent;

  const ResilienceConfig({
    required this.strategy,
    required this.circuitBreakerThreshold,
    required this.circuitBreakerCooldownMs,
    required this.numJitterSamples,
    required this.jitterThresholdPercent,
    required this.stabilityThershold,
    required this.criticalPacketLossPrecent,
  });

  /// Balanced default resilience configuration.
  ///
  /// - Strategy: [`CheckStrategy::Race`] (optimized for speed)
  /// - Jitter Samples: 5 (good balance of accuracy and speed)
  /// - Circuit Breaker: Disabled by default.
  static Future<ResilienceConfig> default_() =>
      RustLib.instance.api.crateApiModelsConfigResilienceConfigDefault();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  /// Creates a new custom [`ResilienceConfig`].
  static Future<ResilienceConfig> newInstance(
          {required CheckStrategy strategy,
          required int circuitBreakerThreshold,
          required BigInt circuitBreakerCooldownMs,
          required int numJitterSamples,
          required double jitterThresholdPercent,
          required int stabilityThershold,
          required double criticalPacketLossPrecent}) =>
      RustLib.instance.api.crateApiModelsConfigResilienceConfigNew(
          strategy: strategy,
          circuitBreakerThreshold: circuitBreakerThreshold,
          circuitBreakerCooldownMs: circuitBreakerCooldownMs,
          numJitterSamples: numJitterSamples,
          jitterThresholdPercent: jitterThresholdPercent,
          stabilityThershold: stabilityThershold,
          criticalPacketLossPrecent: criticalPacketLossPrecent);

  @override
  int get hashCode =>
      strategy.hashCode ^
      circuitBreakerThreshold.hashCode ^
      circuitBreakerCooldownMs.hashCode ^
      numJitterSamples.hashCode ^
      jitterThresholdPercent.hashCode ^
      stabilityThershold.hashCode ^
      criticalPacketLossPrecent.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ResilienceConfig &&
          runtimeType == other.runtimeType &&
          strategy == other.strategy &&
          circuitBreakerThreshold == other.circuitBreakerThreshold &&
          circuitBreakerCooldownMs == other.circuitBreakerCooldownMs &&
          numJitterSamples == other.numJitterSamples &&
          jitterThresholdPercent == other.jitterThresholdPercent &&
          stabilityThershold == other.stabilityThershold &&
          criticalPacketLossPrecent == other.criticalPacketLossPrecent;
}

/// Configuration for security-related network checks and policy enforcement.
///
/// These settings allow the engine to detect environmental factors that might
/// be undesirable or indicate a compromised connection.
class SecurityConfig {
  /// If enabled, the engine will flag connections that originate from a VPN interface.
  ///
  /// Useful for applications that enforce geo-fencing or need to prevent
  /// identity masking.
  final bool blockVpn;

  /// If enabled, performs deep DNS validation to detect hijacking.
  ///
  /// The engine will compare the results of the local system resolver with
  /// a trusted upstream resolver (like Cloudflare or Google). If they differ
  /// significantly for static domains, it flags a potential spoofing attempt.
  final bool detectDnsHijack;

  const SecurityConfig({
    required this.blockVpn,
    required this.detectDnsHijack,
  });

  static Future<SecurityConfig> default_() =>
      RustLib.instance.api.crateApiModelsConfigSecurityConfigDefault();

  @override
  int get hashCode => blockVpn.hashCode ^ detectDnsHijack.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SecurityConfig &&
          runtimeType == other.runtimeType &&
          blockVpn == other.blockVpn &&
          detectDnsHijack == other.detectDnsHijack;
}
