// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: public_member_api_docs, invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `TraceHop`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SecurityFlagsResult>>
abstract class SecurityFlagsResult implements RustOpaqueInterface {
  String get interfaceName;

  bool get isDnsSpoofed;

  bool get isProxyDetected;

  bool get isVpnDetected;

  set interfaceName(String interfaceName);

  set isDnsSpoofed(bool isDnsSpoofed);

  set isProxyDetected(bool isProxyDetected);

  set isVpnDetected(bool isVpnDetected);

  /// Returns a "Safe/Clean" default state where no security issues are detected.
  static Future<SecurityFlagsResult> default_() =>
      RustLib.instance.api.crateApiModelsNetInfoSecurityFlagsResultDefault();
}

/// The result of a captive portal detection probe.
///
/// Captive portals (intercepting gateways) are common in public spaces like
/// airports and cafes. They appear as "connected" to the OS but block all
/// non-authentication traffic.
class CaptivePortalStatus {
  /// True if the engine detected that HTTP requests are being redirected.
  ///
  /// If this is true, the `ConnectionQuality` will likely be set to
  /// [`CaptivePortal`](super::config::ConnectionQuality::CaptivePortal).
  final bool isCaptivePortal;

  /// The destination URL where the traffic was intercepted.
  ///
  /// If available, this is usually the login or "Terms of Service" page.
  /// The application can use this to open a WebView for the user.
  final String? redirectUrl;

  const CaptivePortalStatus({
    required this.isCaptivePortal,
    this.redirectUrl,
  });

  @override
  int get hashCode => isCaptivePortal.hashCode ^ redirectUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CaptivePortalStatus &&
          runtimeType == other.runtimeType &&
          isCaptivePortal == other.isCaptivePortal &&
          redirectUrl == other.redirectUrl;
}

/// Represents the physical or logical medium of the active network connection.
///
/// Understanding the `ConnectionType` is critical for bandwidth management
/// (e.g., deferring large downloads on Cellular) and optimizing latency.
enum ConnectionType {
  /// Connected via a wireless local area network (802.11 WiFi).
  /// Typically implies higher bandwidth and lower cost than cellular.
  wifi,

  /// Connected via a mobile carrier network (e.g., LTE, 5G, 3G).
  /// Usually implies metered data and potentially higher latency.
  cellular,

  /// Connected via a physical RJ45 Ethernet cable.
  /// The most stable and high-performance connection type.
  ethernet,

  /// Connected through a Virtual Private Network (VPN) tunnel.
  /// Indicates that traffic is being routed through an encrypted tunnel
  /// which might mask the true underlying connection type (WiFi/Cellular).
  vpn,

  /// Connected via Bluetooth tethering or a personal area network (PAN).
  /// Characterized by very low bandwidth and limited range.
  bluetooth,

  /// A local loopback interface (typically 127.0.0.1).
  /// Indicates the device is communicating with itself; no external internet.
  loopback,

  /// The connection type could not be identified by the OS or the engine.
  /// This is the fallback for unknown or experimental interface types.
  unknown,
  ;

  /// Returns [`ConnectionType::Unknown`] as the default state.
  static Future<ConnectionType> default_() =>
      RustLib.instance.api.crateApiModelsNetInfoConnectionTypeDefault();
}

/// Internal representation of security-related attributes for the current connection.
///
/// This structure stores raw findings from the engine's security probes.
class SecurityFlags {
  /// True if the active network interface is identified as a tunnel/VPN.
  ///
  /// Detected by looking for interface names like `tun`, `tap`, `ppp`, or `utun`.
  final bool isVpnDetected;

  /// True if the system DNS appears to be providing malicious or redirected results.
  ///
  /// Calculated by comparing local results for known static IPs against
  /// trusted upstream resolvers.
  final bool isDnsSpoofed;

  /// True if a system-wide HTTP or SOCKS proxy is active.
  ///
  /// Proxies can intercept and modify application traffic.
  final bool isProxyDetected;

  /// The system-assigned name of the active network interface.
  /// Examples: `wlan0` (Linux WiFi), `en0` (macOS WiFi), `eth0` (Ethernet).
  final String interfaceName;

  const SecurityFlags({
    required this.isVpnDetected,
    required this.isDnsSpoofed,
    required this.isProxyDetected,
    required this.interfaceName,
  });

  /// Returns a "Safe/Clean" default state where no security issues are detected.
  static Future<SecurityFlags> default_() =>
      RustLib.instance.api.crateApiModelsNetInfoSecurityFlagsDefault();

  @override
  int get hashCode =>
      isVpnDetected.hashCode ^
      isDnsSpoofed.hashCode ^
      isProxyDetected.hashCode ^
      interfaceName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SecurityFlags &&
          runtimeType == other.runtimeType &&
          isVpnDetected == other.isVpnDetected &&
          isDnsSpoofed == other.isDnsSpoofed &&
          isProxyDetected == other.isProxyDetected &&
          interfaceName == other.interfaceName;
}
