// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: public_member_api_docs, invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../../frb_generated.dart';
import 'config.dart';
import 'net_info.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<NetworkReport>>
abstract class NetworkReport implements RustOpaqueInterface {
  ConnectionType get connectionType;

  SecurityFlagsResult get securityFlagsResult;

  NetworkStatus get status;

  List<TargetReport> get targetReports;

  BigInt get timestampMs;

  set connectionType(final ConnectionType connectionType);

  set securityFlagsResult(final SecurityFlagsResult securityFlagsResult);

  set status(final NetworkStatus status);

  set targetReports(final List<TargetReport> targetReports);

  set timestampMs(final BigInt timestampMs);
}

/// A suite of statistical metrics derived from multiple latency samples.
///
/// These metrics provide deep insight into the "health" and consistency
/// of the connection, helping identify subtle issues like bufferbloat
/// or interference.
class LatencyStats {
  const LatencyStats({
    required this.latencyMs,
    required this.jitterMs,
    required this.packetLossPercent,
    required this.stabilityScore,
    this.minLatencyMs,
    this.avgLatencyMs,
    this.maxLatencyMs,
  });

  /// The representative latency value (usually the mean of all successful samples).
  /// Measured in milliseconds.
  final BigInt latencyMs;

  /// The "Jitter" value in milliseconds.
  ///
  /// Jitter is the variation in the delay of received packets (standard deviation).
  /// High jitter (e.g., > 30ms) causes "stuttering" in real-time applications
  /// like VoIP, gaming, and video streaming.
  final BigInt jitterMs;

  /// The percentage of samples (0.0 to 100.0) that failed to return a response.
  ///
  /// Even a small amount of packet loss (1-2%) can significantly degrade
  /// TCP performance and causes noticeable lag in UDP-based services.
  final double packetLossPercent;

  /// The lowest latency recorded across all samples in the cycle.
  /// Represents the "best-case" performance of the current link.
  final BigInt? minLatencyMs;

  /// The arithmetic mean of all successful latency samples.
  final BigInt? avgLatencyMs;

  /// The highest latency recorded across all samples in the cycle.
  /// Often indicates transient congestion or "spikes".
  final BigInt? maxLatencyMs;

  /// A composite score from 0 (broken) to 100 (perfect) representing overall stability.
  ///
  /// The engine calculates this based on jitter consistency and packet loss.
  /// Scores below 70 are typically flagged as [`ConnectionQuality::Unstable`].
  final int stabilityScore;

  @override
  int get hashCode =>
      latencyMs.hashCode ^
      jitterMs.hashCode ^
      packetLossPercent.hashCode ^
      minLatencyMs.hashCode ^
      avgLatencyMs.hashCode ^
      maxLatencyMs.hashCode ^
      stabilityScore.hashCode;

  @override
  bool operator ==(final Object other) =>
      identical(this, other) ||
      other is LatencyStats &&
          runtimeType == other.runtimeType &&
          latencyMs == other.latencyMs &&
          jitterMs == other.jitterMs &&
          packetLossPercent == other.packetLossPercent &&
          minLatencyMs == other.minLatencyMs &&
          avgLatencyMs == other.avgLatencyMs &&
          maxLatencyMs == other.maxLatencyMs &&
          stabilityScore == other.stabilityScore;
}

/// A high-level summary of the network's current state.
///
/// This structure is what most UI layers will use to determine whether to
/// show a "Connected" or "Offline" banner.
class NetworkStatus {
  const NetworkStatus({
    required this.isConnected,
    required this.quality,
    required this.latencyStats,
    required this.winnerTarget,
  });

  /// True if the network is functionally "up" based on the configured strategy.
  final bool isConnected;

  /// The categorical quality of the connection (e.g., Excellent, Poor, Offline).
  ///
  /// Maps raw metrics to user-friendly buckets based on [`QualityThresholds`](super::config::QualityThresholds).
  final ConnectionQuality quality;

  /// Detailed statistical breakdown for performance analysis.
  final LatencyStats latencyStats;

  /// The label of the specific target that responded the fastest in this check.
  ///
  /// Useful for debugging and understanding which server is the
  /// current "closest" endpoint.
  final String winnerTarget;

  @override
  int get hashCode =>
      isConnected.hashCode ^
      quality.hashCode ^
      latencyStats.hashCode ^
      winnerTarget.hashCode;

  @override
  bool operator ==(final Object other) =>
      identical(this, other) ||
      other is NetworkStatus &&
          runtimeType == other.runtimeType &&
          isConnected == other.isConnected &&
          quality == other.quality &&
          latencyStats == other.latencyStats &&
          winnerTarget == other.winnerTarget;
}

/// Detailed outcome of a connectivity check against a specific target.
///
/// Each configured target (e.g., Google DNS, Cloudflare) generates its
/// own `TargetReport` during a check cycle.
class TargetReport {
  const TargetReport({
    required this.label,
    required this.success,
    required this.latencyMs,
    required this.isEssential,
    this.error,
  });

  /// The unique label identifying the target (e.g., "Primary API Gateway").
  final String label;

  /// Indicates whether the target was successfully reached using the specified protocol.
  ///
  /// If `false`, the network is likely either down or this specific
  /// target is experiencing an outage.
  final bool success;

  /// The measured latency in milliseconds for the fastest successful sample.
  ///
  /// This value is 0 if `success` is false.
  final BigInt latencyMs;

  /// A descriptive error message provided by the engine if the check failed.
  ///
  /// Common errors: "Connection Refused", "DNS Resolution Failed", "Timeout".
  final String? error;

  /// Indicates if this target is critical for the overall "Connected" status.
  ///
  /// Failure of an essential target has a higher weight in the
  /// [`CheckStrategy`](super::config::CheckStrategy).
  final bool isEssential;

  @override
  int get hashCode =>
      label.hashCode ^
      success.hashCode ^
      latencyMs.hashCode ^
      error.hashCode ^
      isEssential.hashCode;

  @override
  bool operator ==(final Object other) =>
      identical(this, other) ||
      other is TargetReport &&
          runtimeType == other.runtimeType &&
          label == other.label &&
          success == other.success &&
          latencyMs == other.latencyMs &&
          error == other.error &&
          isEssential == other.isEssential;
}
