// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: public_member_api_docs, invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../../frb_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `eq`, `fmt`, `fmt`

/// Configuration for a specific network endpoint to be monitored.
///
/// A `NetworkTarget` combines an address, a port, and a protocol to
/// define a unique "probe point".
class NetworkTarget {
  const NetworkTarget({
    required this.label,
    required this.host,
    required this.port,
    required this.protocol,
    required this.timeoutMs,
    required this.priority,
    required this.isEssential,
  });

  /// A human-readable identifier (e.g., "Google Cloud DNS", "Internal API").
  /// This label is used in [`TargetReport`](super::report::TargetReport) results.
  final String label;

  /// The remote address to check.
  ///
  /// Can be a fully qualified domain name (e.g., `google.com`) or
  /// a raw IP address (e.g., `1.1.1.1`).
  final String host;

  /// The destination port for the check.
  ///
  /// Common ports:
  /// - 80: Default for HTTP
  /// - 443: Default for HTTPS
  /// - 53: Default for DNS (TCP)
  final int port;

  /// The network protocol to use for this specific probe.
  final TargetProtocol protocol;

  /// The maximum duration (in milliseconds) the engine should wait for a response.
  ///
  /// If no response is received within this window, the target is
  /// marked with a [`TimeoutError`](super::error::NetworkError::TimeoutError).
  final BigInt timeoutMs;

  /// The relative priority of this target (lower numbers = higher priority).
  ///
  /// Currently used for UI sorting and as a hint for the [`Race`](super::config::CheckStrategy::Race)
  /// strategy to decide which targets to fire first.
  final int priority;

  /// If true, a failure of this target is treated as a severe network event.
  ///
  /// Essential targets are the primary triggers for the engine's
  /// "Circuit Breaker" mechanism. Failure of an essential target can
  /// disqualify the entire network status regardless of other successes.
  final bool isEssential;

  @override
  int get hashCode =>
      label.hashCode ^
      host.hashCode ^
      port.hashCode ^
      protocol.hashCode ^
      timeoutMs.hashCode ^
      priority.hashCode ^
      isEssential.hashCode;

  @override
  bool operator ==(final Object other) =>
      identical(this, other) ||
      other is NetworkTarget &&
          runtimeType == other.runtimeType &&
          label == other.label &&
          host == other.host &&
          port == other.port &&
          protocol == other.protocol &&
          timeoutMs == other.timeoutMs &&
          priority == other.priority &&
          isEssential == other.isEssential;
}

/// Supported network protocols for performing reachability probes.
///
/// Each protocol has different performance characteristics and requires
/// different system permissions.
enum TargetProtocol {
  /// Transmission Control Protocol (TCP).
  ///
  /// # Behavior
  /// Performs a full TCP 3-way handshake (`SYN` -> `SYN-ACK` -> `ACK`).
  /// If the connection is established, the target is considered "up".
  ///
  /// # Pros/Cons
  /// + Reliable; works through most firewalls on standard ports (80/443).
  /// - More overhead than ICMP (Ping) as it requires a stateful connection.
  tcp,

  /// Internet Control Message Protocol (ICMP).
  ///
  /// # Behavior
  /// Sends an "Echo Request" (Ping) and waits for an "Echo Reply".
  ///
  /// # Pros/Cons
  /// + Extremely low overhead; the "purest" measure of network latency.
  /// - Often blocked by public firewalls or corporate proxies.
  /// - May require `root` or special capabilities on some Linux systems.
  icmp,

  /// Hypertext Transfer Protocol (HTTP/1.1 or HTTP/2).
  ///
  /// # Behavior
  /// Performs a full HTTP/1.1 `GET` or `HEAD` request to the target URL.
  /// The target is considered "up" if it returns a 2xx (Success) or
  /// 3xx (Redirection) status code.
  ///
  /// # Use Case
  /// Best for validating that a specific web service or API is actually
  /// functional, not just that its port is open.
  http,

  /// Secure Hypertext Transfer Protocol (HTTPS).
  ///
  /// # Behavior
  /// Performs an encrypted request over TLS/SSL. The engine validates
  /// the certificate chain and expiration by default.
  ///
  /// # Pros/Cons
  /// + High confidence; validates that the end-to-end encrypted path is open.
  /// - Highest overhead; requires a full TLS handshake.
  https,
  ;
}
