// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../../frb_generated.dart';
import '../models/config.dart';
import '../models/report.dart';
import '../models/target.dart';

/// Collects multiple latency samples by running checks against all configured targets.
Future<(Uint64List, List<TargetReport>)> collectNetworkSamples({
  required final NetworkConfiguration config,
}) =>
    RustLib.instance.api
        .crateApiEngineSamplerCollectNetworkSamples(config: config);

/// Analyzes the results of a single sample run across all targets.
Future<BigInt?> analyzeSingleSample({
  required final List<TargetReport> reports,
  required final NetworkConfiguration config,
}) =>
    RustLib.instance.api.crateApiEngineSamplerAnalyzeSingleSample(
      reports: reports,
      config: config,
    );
