// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../../frb_generated.dart';
import '../models/config.dart';
import '../models/net_info.dart';
import '../models/target.dart';

/// Runs the DNS hijack check by comparing resolution against trusted resolvers.
Future<void> performDnsSecurityCheck({
  required final NetworkConfiguration config,
  required final SecurityFlagsResult flags,
}) =>
    RustLib.instance.api.crateApiEngineSecurityPerformDnsSecurityCheck(
      config: config,
      flags: flags,
    );
