// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../models/config.dart';
import '../models/net_info.dart';
import '../models/target.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Runs the DNS hijack check by comparing resolution against trusted resolvers.
Future<void> performDnsSecurityCheck(
        {required NetworkConfiguration config,
        required SecurityFlagsResult flags}) =>
    RustLib.instance.api.crateApiEngineSecurityPerformDnsSecurityCheck(
        config: config, flags: flags);
