// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../models/config.dart';
import '../models/report.dart';
import '../models/target.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Evaluates connection quality based on a latency value and a set of thresholds.
///
/// # Arguments
///
/// * `latency` - The latency value in milliseconds.
/// * `threshold` - A reference to the [QualityThresholds] to compare against.
///
/// # Returns
///
/// A [ConnectionQuality] enum variant representing the quality level.
Future<ConnectionQuality> evaluateQuality(
        {required BigInt latency, required QualityThresholds threshold}) =>
    RustLib.instance.api.crateApiAnalysisQualityEvaluateQuality(
        latency: latency, threshold: threshold);

/// Evaluates the final network quality by combining speed, stability, and loss.
Future<ConnectionQuality> evaluateNetworkQuality(
        {required bool isConnected,
        required LatencyStats stats,
        required NetworkConfiguration config}) =>
    RustLib.instance.api.crateApiAnalysisQualityEvaluateNetworkQuality(
        isConnected: isConnected, stats: stats, config: config);
