// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../models/config.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Evaluates connection quality based on latency against a set of thresholds.
Future<ConnectionQuality> evaluateQuality(
        {required BigInt latency, required QualityThresholds threshold}) =>
    RustLib.instance.api.crateApiAnalysisQualityEvaluateQuality(
        latency: latency, threshold: threshold);

/// Calculates statistical metrics for a series of latency samples.
///
/// Returns a tuple containing: (min, max, mean, standard_deviation).
Future<(BigInt?, BigInt?, BigInt?, double?)> calculateJitterStats(
        {required Uint64List latencies}) =>
    RustLib.instance.api
        .crateApiAnalysisQualityCalculateJitterStats(latencies: latencies);
