// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../models/config.dart';
import '../models/report.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `lerp`

/// Calculates statistical metrics for a series of latency samples.
///
/// This function computes the minimum, maximum, and mean latency, along with the
/// standard deviation, which is used as a measure of jitter.
///
/// # Arguments
///
/// * `latencies` - A slice of u64 latency values in milliseconds.
///
/// # Returns
///
/// A tuple containing:
/// 1. `Option<u64>`: Minimum latency.
/// 2. `Option<u64>`: Maximum latency.
/// 3. `Option<u64>`: Mean (average) latency.
/// 4. `Option<f64>`: Standard deviation (jitter).
Future<(BigInt?, BigInt?, BigInt?, double?)> calculateJitterStats(
        {required Uint64List latencies}) =>
    RustLib.instance.api
        .crateApiAnalysisStatsCalculateJitterStats(latencies: latencies);

/// Computes final latency and stability statistics from a set of samples.
///
/// The scoring system is tuned for: Home WiFi + Mobile 4G/5G networks.
/// Priority weights:
/// - Latency Absolute:   30% (penalizes high latency values directly)
/// - Latency Stability:  25% (measures variance / coefficient of variation)
/// - Loss Score:         25% (measures reliability)
/// - Jitter Score:       15% (measures packet arrival consistency)
/// - Spike Score:          5% (measures outlier impact)
Future<LatencyStats> computeLatencyStats(
        {required Uint64List latencies,
        required int totalExpectedSamples,
        required QualityThresholds thresholds}) =>
    RustLib.instance.api.crateApiAnalysisStatsComputeLatencyStats(
        latencies: latencies,
        totalExpectedSamples: totalExpectedSamples,
        thresholds: thresholds);
