// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/engine.dart';
import 'api/models.dart';
import 'api/utils.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 967474185;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'rust_lib_network_reachability',
    ioDirectory: 'rust/target/release/',
    webPrefix: 'pkg/',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<(BigInt?, BigInt?, BigInt?, double?)> crateApiEngineCalculateJitter(
      {required Uint64List latencies});

  Future<CaptivePortalStatus> crateApiUtilsCheckForCaptivePortal(
      {required BigInt timeoutMs});

  Future<NetworkReport> crateApiEngineCheckNetwork(
      {required NetwrokConfiguration config});

  Future<(NetworkMetadata, ConnectionType)>
      crateApiUtilsDetectNetworkMetadata();

  Future<ConnectionQuality> crateApiUtilsEvaluateQuality(
      {required BigInt latency, required QualityThresholds threshold});

  Future<NetwrokConfiguration> crateApiModelsNetwrokConfigurationDefault();

  Future<QualityThresholds> crateApiModelsQualityThresholdsDefault();

  Future<List<LocalDevice>> crateApiUtilsScanLocalNetwork(
      {required String subnet,
      required int scanPort,
      required BigInt timeoutMs});

  Future<List<TraceHop>> crateApiUtilsTraceRoute(
      {required String host,
      required int maxHops,
      required BigInt timeoutPerHopMs});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<(BigInt?, BigInt?, BigInt?, double?)> crateApiEngineCalculateJitter(
      {required Uint64List latencies}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_u_64_strict(latencies, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 1, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData:
            sse_decode_record_opt_box_autoadd_u_64_opt_box_autoadd_u_64_opt_box_autoadd_u_64_opt_box_autoadd_f_64,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiEngineCalculateJitterConstMeta,
      argValues: [latencies],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiEngineCalculateJitterConstMeta =>
      const TaskConstMeta(
        debugName: "_calculate_jitter",
        argNames: ["latencies"],
      );

  @override
  Future<CaptivePortalStatus> crateApiUtilsCheckForCaptivePortal(
      {required BigInt timeoutMs}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_u_64(timeoutMs, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 2, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_captive_portal_status,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiUtilsCheckForCaptivePortalConstMeta,
      argValues: [timeoutMs],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiUtilsCheckForCaptivePortalConstMeta =>
      const TaskConstMeta(
        debugName: "check_for_captive_portal",
        argNames: ["timeoutMs"],
      );

  @override
  Future<NetworkReport> crateApiEngineCheckNetwork(
      {required NetwrokConfiguration config}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_netwrok_configuration(config, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 3, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_network_report,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiEngineCheckNetworkConstMeta,
      argValues: [config],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiEngineCheckNetworkConstMeta => const TaskConstMeta(
        debugName: "check_network",
        argNames: ["config"],
      );

  @override
  Future<(NetworkMetadata, ConnectionType)>
      crateApiUtilsDetectNetworkMetadata() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_record_network_metadata_connection_type,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiUtilsDetectNetworkMetadataConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiUtilsDetectNetworkMetadataConstMeta =>
      const TaskConstMeta(
        debugName: "detect_network_metadata",
        argNames: [],
      );

  @override
  Future<ConnectionQuality> crateApiUtilsEvaluateQuality(
      {required BigInt latency, required QualityThresholds threshold}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_u_64(latency, serializer);
        sse_encode_box_autoadd_quality_thresholds(threshold, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_connection_quality,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiUtilsEvaluateQualityConstMeta,
      argValues: [latency, threshold],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiUtilsEvaluateQualityConstMeta =>
      const TaskConstMeta(
        debugName: "evaluate_quality",
        argNames: ["latency", "threshold"],
      );

  @override
  Future<NetwrokConfiguration> crateApiModelsNetwrokConfigurationDefault() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 6, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_netwrok_configuration,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiModelsNetwrokConfigurationDefaultConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiModelsNetwrokConfigurationDefaultConstMeta =>
      const TaskConstMeta(
        debugName: "netwrok_configuration_default",
        argNames: [],
      );

  @override
  Future<QualityThresholds> crateApiModelsQualityThresholdsDefault() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 7, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_quality_thresholds,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiModelsQualityThresholdsDefaultConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiModelsQualityThresholdsDefaultConstMeta =>
      const TaskConstMeta(
        debugName: "quality_thresholds_default",
        argNames: [],
      );

  @override
  Future<List<LocalDevice>> crateApiUtilsScanLocalNetwork(
      {required String subnet,
      required int scanPort,
      required BigInt timeoutMs}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(subnet, serializer);
        sse_encode_u_16(scanPort, serializer);
        sse_encode_u_64(timeoutMs, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 8, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_local_device,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiUtilsScanLocalNetworkConstMeta,
      argValues: [subnet, scanPort, timeoutMs],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiUtilsScanLocalNetworkConstMeta =>
      const TaskConstMeta(
        debugName: "scan_local_network",
        argNames: ["subnet", "scanPort", "timeoutMs"],
      );

  @override
  Future<List<TraceHop>> crateApiUtilsTraceRoute(
      {required String host,
      required int maxHops,
      required BigInt timeoutPerHopMs}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(host, serializer);
        sse_encode_u_8(maxHops, serializer);
        sse_encode_u_64(timeoutPerHopMs, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 9, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_trace_hop,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiUtilsTraceRouteConstMeta,
      argValues: [host, maxHops, timeoutPerHopMs],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiUtilsTraceRouteConstMeta => const TaskConstMeta(
        debugName: "trace_route",
        argNames: ["host", "maxHops", "timeoutPerHopMs"],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  NetwrokConfiguration dco_decode_box_autoadd_netwrok_configuration(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_netwrok_configuration(raw);
  }

  @protected
  QualityThresholds dco_decode_box_autoadd_quality_thresholds(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_quality_thresholds(raw);
  }

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_u_64(raw);
  }

  @protected
  CaptivePortalStatus dco_decode_captive_portal_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return CaptivePortalStatus(
      isCaptivePortal: dco_decode_bool(arr[0]),
      redirectUrl: dco_decode_opt_String(arr[1]),
    );
  }

  @protected
  CheckStrategy dco_decode_check_strategy(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CheckStrategy.values[raw as int];
  }

  @protected
  ConnectionQuality dco_decode_connection_quality(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ConnectionQuality.values[raw as int];
  }

  @protected
  ConnectionType dco_decode_connection_type(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ConnectionType.values[raw as int];
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<LocalDevice> dco_decode_list_local_device(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_local_device).toList();
  }

  @protected
  List<NetworkTarget> dco_decode_list_network_target(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_network_target).toList();
  }

  @protected
  Uint64List dco_decode_list_prim_u_64_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeUint64List(raw);
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<TargetReport> dco_decode_list_target_report(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_target_report).toList();
  }

  @protected
  List<TraceHop> dco_decode_list_trace_hop(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_trace_hop).toList();
  }

  @protected
  LocalDevice dco_decode_local_device(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return LocalDevice(
      ipAddress: dco_decode_String(arr[0]),
      hostname: dco_decode_opt_String(arr[1]),
      macAddress: dco_decode_opt_String(arr[2]),
    );
  }

  @protected
  NetworkMetadata dco_decode_network_metadata(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return NetworkMetadata(
      isVpn: dco_decode_bool(arr[0]),
      interfaceName: dco_decode_String(arr[1]),
    );
  }

  @protected
  NetworkReport dco_decode_network_report(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return NetworkReport(
      timestampMs: dco_decode_u_64(arr[0]),
      status: dco_decode_network_status(arr[1]),
      connectionType: dco_decode_connection_type(arr[2]),
      metadata: dco_decode_network_metadata(arr[3]),
      targetReports: dco_decode_list_target_report(arr[4]),
    );
  }

  @protected
  NetworkStatus dco_decode_network_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return NetworkStatus(
      isConnected: dco_decode_bool(arr[0]),
      quality: dco_decode_connection_quality(arr[1]),
      latencyMs: dco_decode_u_64(arr[2]),
      winnerTarget: dco_decode_String(arr[3]),
      minLatencyMs: dco_decode_opt_box_autoadd_u_64(arr[4]),
      maxLatencyMs: dco_decode_opt_box_autoadd_u_64(arr[5]),
      meanLatencyMs: dco_decode_opt_box_autoadd_u_64(arr[6]),
      stdDevLatencyMs: dco_decode_opt_box_autoadd_f_64(arr[7]),
    );
  }

  @protected
  NetworkTarget dco_decode_network_target(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return NetworkTarget(
      label: dco_decode_String(arr[0]),
      host: dco_decode_String(arr[1]),
      port: dco_decode_u_16(arr[2]),
      protocol: dco_decode_target_protocol(arr[3]),
      timeoutMs: dco_decode_u_64(arr[4]),
      priority: dco_decode_u_8(arr[5]),
      isEssential: dco_decode_bool(arr[6]),
    );
  }

  @protected
  NetwrokConfiguration dco_decode_netwrok_configuration(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return NetwrokConfiguration(
      targets: dco_decode_list_network_target(arr[0]),
      checkStrategy: dco_decode_check_strategy(arr[1]),
      qualityThreshold: dco_decode_quality_thresholds(arr[2]),
      checkIntervalMs: dco_decode_u_64(arr[3]),
      blockRequestWhenPoor: dco_decode_bool(arr[4]),
      numJitterSamples: dco_decode_u_8(arr[5]),
      jitterThresholdPercent: dco_decode_f_64(arr[6]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_f_64(raw);
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_64(raw);
  }

  @protected
  QualityThresholds dco_decode_quality_thresholds(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return QualityThresholds(
      excellent: dco_decode_u_64(arr[0]),
      great: dco_decode_u_64(arr[1]),
      good: dco_decode_u_64(arr[2]),
      moderate: dco_decode_u_64(arr[3]),
      poor: dco_decode_u_64(arr[4]),
    );
  }

  @protected
  (NetworkMetadata, ConnectionType)
      dco_decode_record_network_metadata_connection_type(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (
      dco_decode_network_metadata(arr[0]),
      dco_decode_connection_type(arr[1]),
    );
  }

  @protected
  (
    BigInt?,
    BigInt?,
    BigInt?,
    double?
  ) dco_decode_record_opt_box_autoadd_u_64_opt_box_autoadd_u_64_opt_box_autoadd_u_64_opt_box_autoadd_f_64(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4) {
      throw Exception('Expected 4 elements, got ${arr.length}');
    }
    return (
      dco_decode_opt_box_autoadd_u_64(arr[0]),
      dco_decode_opt_box_autoadd_u_64(arr[1]),
      dco_decode_opt_box_autoadd_u_64(arr[2]),
      dco_decode_opt_box_autoadd_f_64(arr[3]),
    );
  }

  @protected
  TargetProtocol dco_decode_target_protocol(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TargetProtocol.values[raw as int];
  }

  @protected
  TargetReport dco_decode_target_report(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return TargetReport(
      label: dco_decode_String(arr[0]),
      success: dco_decode_bool(arr[1]),
      latencyMs: dco_decode_opt_box_autoadd_u_64(arr[2]),
      error: dco_decode_opt_String(arr[3]),
      isEssential: dco_decode_bool(arr[4]),
    );
  }

  @protected
  TraceHop dco_decode_trace_hop(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return TraceHop(
      hopNumber: dco_decode_u_8(arr[0]),
      ipAddress: dco_decode_String(arr[1]),
      hostname: dco_decode_opt_String(arr[2]),
      latencyMs: dco_decode_opt_box_autoadd_u_64(arr[3]),
    );
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_f_64(deserializer));
  }

  @protected
  NetwrokConfiguration sse_decode_box_autoadd_netwrok_configuration(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_netwrok_configuration(deserializer));
  }

  @protected
  QualityThresholds sse_decode_box_autoadd_quality_thresholds(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_quality_thresholds(deserializer));
  }

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_64(deserializer));
  }

  @protected
  CaptivePortalStatus sse_decode_captive_portal_status(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_isCaptivePortal = sse_decode_bool(deserializer);
    var var_redirectUrl = sse_decode_opt_String(deserializer);
    return CaptivePortalStatus(
        isCaptivePortal: var_isCaptivePortal, redirectUrl: var_redirectUrl);
  }

  @protected
  CheckStrategy sse_decode_check_strategy(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return CheckStrategy.values[inner];
  }

  @protected
  ConnectionQuality sse_decode_connection_quality(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ConnectionQuality.values[inner];
  }

  @protected
  ConnectionType sse_decode_connection_type(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ConnectionType.values[inner];
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<LocalDevice> sse_decode_list_local_device(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <LocalDevice>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_local_device(deserializer));
    }
    return ans_;
  }

  @protected
  List<NetworkTarget> sse_decode_list_network_target(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <NetworkTarget>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_network_target(deserializer));
    }
    return ans_;
  }

  @protected
  Uint64List sse_decode_list_prim_u_64_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint64List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<TargetReport> sse_decode_list_target_report(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TargetReport>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_target_report(deserializer));
    }
    return ans_;
  }

  @protected
  List<TraceHop> sse_decode_list_trace_hop(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TraceHop>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_trace_hop(deserializer));
    }
    return ans_;
  }

  @protected
  LocalDevice sse_decode_local_device(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_ipAddress = sse_decode_String(deserializer);
    var var_hostname = sse_decode_opt_String(deserializer);
    var var_macAddress = sse_decode_opt_String(deserializer);
    return LocalDevice(
        ipAddress: var_ipAddress,
        hostname: var_hostname,
        macAddress: var_macAddress);
  }

  @protected
  NetworkMetadata sse_decode_network_metadata(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_isVpn = sse_decode_bool(deserializer);
    var var_interfaceName = sse_decode_String(deserializer);
    return NetworkMetadata(isVpn: var_isVpn, interfaceName: var_interfaceName);
  }

  @protected
  NetworkReport sse_decode_network_report(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_timestampMs = sse_decode_u_64(deserializer);
    var var_status = sse_decode_network_status(deserializer);
    var var_connectionType = sse_decode_connection_type(deserializer);
    var var_metadata = sse_decode_network_metadata(deserializer);
    var var_targetReports = sse_decode_list_target_report(deserializer);
    return NetworkReport(
        timestampMs: var_timestampMs,
        status: var_status,
        connectionType: var_connectionType,
        metadata: var_metadata,
        targetReports: var_targetReports);
  }

  @protected
  NetworkStatus sse_decode_network_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_isConnected = sse_decode_bool(deserializer);
    var var_quality = sse_decode_connection_quality(deserializer);
    var var_latencyMs = sse_decode_u_64(deserializer);
    var var_winnerTarget = sse_decode_String(deserializer);
    var var_minLatencyMs = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_maxLatencyMs = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_meanLatencyMs = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_stdDevLatencyMs = sse_decode_opt_box_autoadd_f_64(deserializer);
    return NetworkStatus(
        isConnected: var_isConnected,
        quality: var_quality,
        latencyMs: var_latencyMs,
        winnerTarget: var_winnerTarget,
        minLatencyMs: var_minLatencyMs,
        maxLatencyMs: var_maxLatencyMs,
        meanLatencyMs: var_meanLatencyMs,
        stdDevLatencyMs: var_stdDevLatencyMs);
  }

  @protected
  NetworkTarget sse_decode_network_target(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_label = sse_decode_String(deserializer);
    var var_host = sse_decode_String(deserializer);
    var var_port = sse_decode_u_16(deserializer);
    var var_protocol = sse_decode_target_protocol(deserializer);
    var var_timeoutMs = sse_decode_u_64(deserializer);
    var var_priority = sse_decode_u_8(deserializer);
    var var_isEssential = sse_decode_bool(deserializer);
    return NetworkTarget(
        label: var_label,
        host: var_host,
        port: var_port,
        protocol: var_protocol,
        timeoutMs: var_timeoutMs,
        priority: var_priority,
        isEssential: var_isEssential);
  }

  @protected
  NetwrokConfiguration sse_decode_netwrok_configuration(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_targets = sse_decode_list_network_target(deserializer);
    var var_checkStrategy = sse_decode_check_strategy(deserializer);
    var var_qualityThreshold = sse_decode_quality_thresholds(deserializer);
    var var_checkIntervalMs = sse_decode_u_64(deserializer);
    var var_blockRequestWhenPoor = sse_decode_bool(deserializer);
    var var_numJitterSamples = sse_decode_u_8(deserializer);
    var var_jitterThresholdPercent = sse_decode_f_64(deserializer);
    return NetwrokConfiguration(
        targets: var_targets,
        checkStrategy: var_checkStrategy,
        qualityThreshold: var_qualityThreshold,
        checkIntervalMs: var_checkIntervalMs,
        blockRequestWhenPoor: var_blockRequestWhenPoor,
        numJitterSamples: var_numJitterSamples,
        jitterThresholdPercent: var_jitterThresholdPercent);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_f_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  QualityThresholds sse_decode_quality_thresholds(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_excellent = sse_decode_u_64(deserializer);
    var var_great = sse_decode_u_64(deserializer);
    var var_good = sse_decode_u_64(deserializer);
    var var_moderate = sse_decode_u_64(deserializer);
    var var_poor = sse_decode_u_64(deserializer);
    return QualityThresholds(
        excellent: var_excellent,
        great: var_great,
        good: var_good,
        moderate: var_moderate,
        poor: var_poor);
  }

  @protected
  (NetworkMetadata, ConnectionType)
      sse_decode_record_network_metadata_connection_type(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_network_metadata(deserializer);
    var var_field1 = sse_decode_connection_type(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  (
    BigInt?,
    BigInt?,
    BigInt?,
    double?
  ) sse_decode_record_opt_box_autoadd_u_64_opt_box_autoadd_u_64_opt_box_autoadd_u_64_opt_box_autoadd_f_64(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_field1 = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_field2 = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_field3 = sse_decode_opt_box_autoadd_f_64(deserializer);
    return (var_field0, var_field1, var_field2, var_field3);
  }

  @protected
  TargetProtocol sse_decode_target_protocol(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return TargetProtocol.values[inner];
  }

  @protected
  TargetReport sse_decode_target_report(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_label = sse_decode_String(deserializer);
    var var_success = sse_decode_bool(deserializer);
    var var_latencyMs = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_error = sse_decode_opt_String(deserializer);
    var var_isEssential = sse_decode_bool(deserializer);
    return TargetReport(
        label: var_label,
        success: var_success,
        latencyMs: var_latencyMs,
        error: var_error,
        isEssential: var_isEssential);
  }

  @protected
  TraceHop sse_decode_trace_hop(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_hopNumber = sse_decode_u_8(deserializer);
    var var_ipAddress = sse_decode_String(deserializer);
    var var_hostname = sse_decode_opt_String(deserializer);
    var var_latencyMs = sse_decode_opt_box_autoadd_u_64(deserializer);
    return TraceHop(
        hopNumber: var_hopNumber,
        ipAddress: var_ipAddress,
        hostname: var_hostname,
        latencyMs: var_latencyMs);
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_netwrok_configuration(
      NetwrokConfiguration self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_netwrok_configuration(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_quality_thresholds(
      QualityThresholds self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_quality_thresholds(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self, serializer);
  }

  @protected
  void sse_encode_captive_portal_status(
      CaptivePortalStatus self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.isCaptivePortal, serializer);
    sse_encode_opt_String(self.redirectUrl, serializer);
  }

  @protected
  void sse_encode_check_strategy(CheckStrategy self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_connection_quality(
      ConnectionQuality self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_connection_type(
      ConnectionType self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_local_device(
      List<LocalDevice> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_local_device(item, serializer);
    }
  }

  @protected
  void sse_encode_list_network_target(
      List<NetworkTarget> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_network_target(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_64_strict(
      Uint64List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint64List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_target_report(
      List<TargetReport> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_target_report(item, serializer);
    }
  }

  @protected
  void sse_encode_list_trace_hop(
      List<TraceHop> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_trace_hop(item, serializer);
    }
  }

  @protected
  void sse_encode_local_device(LocalDevice self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.ipAddress, serializer);
    sse_encode_opt_String(self.hostname, serializer);
    sse_encode_opt_String(self.macAddress, serializer);
  }

  @protected
  void sse_encode_network_metadata(
      NetworkMetadata self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.isVpn, serializer);
    sse_encode_String(self.interfaceName, serializer);
  }

  @protected
  void sse_encode_network_report(NetworkReport self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.timestampMs, serializer);
    sse_encode_network_status(self.status, serializer);
    sse_encode_connection_type(self.connectionType, serializer);
    sse_encode_network_metadata(self.metadata, serializer);
    sse_encode_list_target_report(self.targetReports, serializer);
  }

  @protected
  void sse_encode_network_status(NetworkStatus self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.isConnected, serializer);
    sse_encode_connection_quality(self.quality, serializer);
    sse_encode_u_64(self.latencyMs, serializer);
    sse_encode_String(self.winnerTarget, serializer);
    sse_encode_opt_box_autoadd_u_64(self.minLatencyMs, serializer);
    sse_encode_opt_box_autoadd_u_64(self.maxLatencyMs, serializer);
    sse_encode_opt_box_autoadd_u_64(self.meanLatencyMs, serializer);
    sse_encode_opt_box_autoadd_f_64(self.stdDevLatencyMs, serializer);
  }

  @protected
  void sse_encode_network_target(NetworkTarget self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.label, serializer);
    sse_encode_String(self.host, serializer);
    sse_encode_u_16(self.port, serializer);
    sse_encode_target_protocol(self.protocol, serializer);
    sse_encode_u_64(self.timeoutMs, serializer);
    sse_encode_u_8(self.priority, serializer);
    sse_encode_bool(self.isEssential, serializer);
  }

  @protected
  void sse_encode_netwrok_configuration(
      NetwrokConfiguration self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_network_target(self.targets, serializer);
    sse_encode_check_strategy(self.checkStrategy, serializer);
    sse_encode_quality_thresholds(self.qualityThreshold, serializer);
    sse_encode_u_64(self.checkIntervalMs, serializer);
    sse_encode_bool(self.blockRequestWhenPoor, serializer);
    sse_encode_u_8(self.numJitterSamples, serializer);
    sse_encode_f_64(self.jitterThresholdPercent, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_f_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_64(self, serializer);
    }
  }

  @protected
  void sse_encode_quality_thresholds(
      QualityThresholds self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.excellent, serializer);
    sse_encode_u_64(self.great, serializer);
    sse_encode_u_64(self.good, serializer);
    sse_encode_u_64(self.moderate, serializer);
    sse_encode_u_64(self.poor, serializer);
  }

  @protected
  void sse_encode_record_network_metadata_connection_type(
      (NetworkMetadata, ConnectionType) self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_network_metadata(self.$1, serializer);
    sse_encode_connection_type(self.$2, serializer);
  }

  @protected
  void
      sse_encode_record_opt_box_autoadd_u_64_opt_box_autoadd_u_64_opt_box_autoadd_u_64_opt_box_autoadd_f_64(
          (BigInt?, BigInt?, BigInt?, double?) self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_box_autoadd_u_64(self.$1, serializer);
    sse_encode_opt_box_autoadd_u_64(self.$2, serializer);
    sse_encode_opt_box_autoadd_u_64(self.$3, serializer);
    sse_encode_opt_box_autoadd_f_64(self.$4, serializer);
  }

  @protected
  void sse_encode_target_protocol(
      TargetProtocol self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_target_report(TargetReport self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.label, serializer);
    sse_encode_bool(self.success, serializer);
    sse_encode_opt_box_autoadd_u_64(self.latencyMs, serializer);
    sse_encode_opt_String(self.error, serializer);
    sse_encode_bool(self.isEssential, serializer);
  }

  @protected
  void sse_encode_trace_hop(TraceHop self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_8(self.hopNumber, serializer);
    sse_encode_String(self.ipAddress, serializer);
    sse_encode_opt_String(self.hostname, serializer);
    sse_encode_opt_box_autoadd_u_64(self.latencyMs, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
