// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/analysis/quality.dart';
import 'api/engine.dart';
import 'api/models/config.dart';
import 'api/models/net_info.dart';
import 'api/models/report.dart';
import 'api/models/target.dart';
import 'api/probes/captive_portal.dart';
import 'api/probes/dns.dart';
import 'api/probes/interface.dart';
import 'api/probes/local_scan.dart';
import 'api/probes/target.dart';
import 'api/probes/traceroute.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  NetworkConfiguration dco_decode_box_autoadd_network_configuration(
      dynamic raw);

  @protected
  NetworkTarget dco_decode_box_autoadd_network_target(dynamic raw);

  @protected
  QualityThresholds dco_decode_box_autoadd_quality_thresholds(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  CaptivePortalStatus dco_decode_captive_portal_status(dynamic raw);

  @protected
  CheckStrategy dco_decode_check_strategy(dynamic raw);

  @protected
  ConnectionQuality dco_decode_connection_quality(dynamic raw);

  @protected
  ConnectionType dco_decode_connection_type(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  LatencyStats dco_decode_latency_stats(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<LocalDevice> dco_decode_list_local_device(dynamic raw);

  @protected
  List<NetworkTarget> dco_decode_list_network_target(dynamic raw);

  @protected
  Uint64List dco_decode_list_prim_u_64_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<TargetReport> dco_decode_list_target_report(dynamic raw);

  @protected
  List<TraceHop> dco_decode_list_trace_hop(dynamic raw);

  @protected
  LocalDevice dco_decode_local_device(dynamic raw);

  @protected
  NetworkConfiguration dco_decode_network_configuration(dynamic raw);

  @protected
  NetworkReport dco_decode_network_report(dynamic raw);

  @protected
  NetworkStatus dco_decode_network_status(dynamic raw);

  @protected
  NetworkTarget dco_decode_network_target(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  QualityThresholds dco_decode_quality_thresholds(dynamic raw);

  @protected
  (
    BigInt?,
    BigInt?,
    BigInt?,
    double?
  ) dco_decode_record_opt_box_autoadd_u_64_opt_box_autoadd_u_64_opt_box_autoadd_u_64_opt_box_autoadd_f_64(
      dynamic raw);

  @protected
  (SecurityFlags, ConnectionType)
      dco_decode_record_security_flags_connection_type(dynamic raw);

  @protected
  ResilienceConfig dco_decode_resilience_config(dynamic raw);

  @protected
  SecurityConfig dco_decode_security_config(dynamic raw);

  @protected
  SecurityFlags dco_decode_security_flags(dynamic raw);

  @protected
  TargetProtocol dco_decode_target_protocol(dynamic raw);

  @protected
  TargetReport dco_decode_target_report(dynamic raw);

  @protected
  TraceHop dco_decode_trace_hop(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  NetworkConfiguration sse_decode_box_autoadd_network_configuration(
      SseDeserializer deserializer);

  @protected
  NetworkTarget sse_decode_box_autoadd_network_target(
      SseDeserializer deserializer);

  @protected
  QualityThresholds sse_decode_box_autoadd_quality_thresholds(
      SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  CaptivePortalStatus sse_decode_captive_portal_status(
      SseDeserializer deserializer);

  @protected
  CheckStrategy sse_decode_check_strategy(SseDeserializer deserializer);

  @protected
  ConnectionQuality sse_decode_connection_quality(SseDeserializer deserializer);

  @protected
  ConnectionType sse_decode_connection_type(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  LatencyStats sse_decode_latency_stats(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<LocalDevice> sse_decode_list_local_device(SseDeserializer deserializer);

  @protected
  List<NetworkTarget> sse_decode_list_network_target(
      SseDeserializer deserializer);

  @protected
  Uint64List sse_decode_list_prim_u_64_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<TargetReport> sse_decode_list_target_report(
      SseDeserializer deserializer);

  @protected
  List<TraceHop> sse_decode_list_trace_hop(SseDeserializer deserializer);

  @protected
  LocalDevice sse_decode_local_device(SseDeserializer deserializer);

  @protected
  NetworkConfiguration sse_decode_network_configuration(
      SseDeserializer deserializer);

  @protected
  NetworkReport sse_decode_network_report(SseDeserializer deserializer);

  @protected
  NetworkStatus sse_decode_network_status(SseDeserializer deserializer);

  @protected
  NetworkTarget sse_decode_network_target(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  QualityThresholds sse_decode_quality_thresholds(SseDeserializer deserializer);

  @protected
  (
    BigInt?,
    BigInt?,
    BigInt?,
    double?
  ) sse_decode_record_opt_box_autoadd_u_64_opt_box_autoadd_u_64_opt_box_autoadd_u_64_opt_box_autoadd_f_64(
      SseDeserializer deserializer);

  @protected
  (SecurityFlags, ConnectionType)
      sse_decode_record_security_flags_connection_type(
          SseDeserializer deserializer);

  @protected
  ResilienceConfig sse_decode_resilience_config(SseDeserializer deserializer);

  @protected
  SecurityConfig sse_decode_security_config(SseDeserializer deserializer);

  @protected
  SecurityFlags sse_decode_security_flags(SseDeserializer deserializer);

  @protected
  TargetProtocol sse_decode_target_protocol(SseDeserializer deserializer);

  @protected
  TargetReport sse_decode_target_report(SseDeserializer deserializer);

  @protected
  TraceHop sse_decode_trace_hop(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_network_configuration(
      NetworkConfiguration self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_network_target(
      NetworkTarget self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_quality_thresholds(
      QualityThresholds self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_captive_portal_status(
      CaptivePortalStatus self, SseSerializer serializer);

  @protected
  void sse_encode_check_strategy(CheckStrategy self, SseSerializer serializer);

  @protected
  void sse_encode_connection_quality(
      ConnectionQuality self, SseSerializer serializer);

  @protected
  void sse_encode_connection_type(
      ConnectionType self, SseSerializer serializer);

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_latency_stats(LatencyStats self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_local_device(
      List<LocalDevice> self, SseSerializer serializer);

  @protected
  void sse_encode_list_network_target(
      List<NetworkTarget> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_64_strict(
      Uint64List self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_list_target_report(
      List<TargetReport> self, SseSerializer serializer);

  @protected
  void sse_encode_list_trace_hop(List<TraceHop> self, SseSerializer serializer);

  @protected
  void sse_encode_local_device(LocalDevice self, SseSerializer serializer);

  @protected
  void sse_encode_network_configuration(
      NetworkConfiguration self, SseSerializer serializer);

  @protected
  void sse_encode_network_report(NetworkReport self, SseSerializer serializer);

  @protected
  void sse_encode_network_status(NetworkStatus self, SseSerializer serializer);

  @protected
  void sse_encode_network_target(NetworkTarget self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_quality_thresholds(
      QualityThresholds self, SseSerializer serializer);

  @protected
  void
      sse_encode_record_opt_box_autoadd_u_64_opt_box_autoadd_u_64_opt_box_autoadd_u_64_opt_box_autoadd_f_64(
          (BigInt?, BigInt?, BigInt?, double?) self, SseSerializer serializer);

  @protected
  void sse_encode_record_security_flags_connection_type(
      (SecurityFlags, ConnectionType) self, SseSerializer serializer);

  @protected
  void sse_encode_resilience_config(
      ResilienceConfig self, SseSerializer serializer);

  @protected
  void sse_encode_security_config(
      SecurityConfig self, SseSerializer serializer);

  @protected
  void sse_encode_security_flags(SecurityFlags self, SseSerializer serializer);

  @protected
  void sse_encode_target_protocol(
      TargetProtocol self, SseSerializer serializer);

  @protected
  void sse_encode_target_report(TargetReport self, SseSerializer serializer);

  @protected
  void sse_encode_trace_hop(TraceHop self, SseSerializer serializer);

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;
}
