// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models/config.dart';
import 'models/report.dart';
import 'models/target.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// The main entry point for running a comprehensive network check.
///
/// This function orchestrates the entire check process:
/// 1. Collects latency samples via [sampler::collect_network_samples].
/// 2. Computes statistics via [analysis::compute_latency_stats].
/// 3. Evaluates quality via [analysis::evaluate_network_quality].
/// 4. Detects interface security and type.
/// 5. Compiles a final [NetworkReport].
Future<NetworkReport> checkNetwork({required NetworkConfiguration config}) =>
    RustLib.instance.api.crateApiEngineCheckNetwork(config: config);
