// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ConnectionQuality`, `ConnectionType`, `NetworkMetadata`, `NetworkReport`, `NetworkStatus`, `TargetReport`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

enum CheckStrategy { race, consensus }

class Configuration {
  final List<NetworkTarget> targets;
  final CheckStrategy checkStrategy;
  final QualityThresholds qualityThreshold;
  final int checkIntervalMs;
  final bool blockRequestWhenPoor;

  const Configuration({
    required this.targets,
    required this.checkStrategy,
    required this.qualityThreshold,
    required this.checkIntervalMs,
    required this.blockRequestWhenPoor,
  });

  static Future<Configuration> default_() =>
      RustLib.instance.api.crateApiModelsConfigurationDefault();

  @override
  int get hashCode =>
      targets.hashCode ^
      checkStrategy.hashCode ^
      qualityThreshold.hashCode ^
      checkIntervalMs.hashCode ^
      blockRequestWhenPoor.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Configuration &&
          runtimeType == other.runtimeType &&
          targets == other.targets &&
          checkStrategy == other.checkStrategy &&
          qualityThreshold == other.qualityThreshold &&
          checkIntervalMs == other.checkIntervalMs &&
          blockRequestWhenPoor == other.blockRequestWhenPoor;
}

class NetworkTarget {
  final String label;
  final String host;
  final int port;
  final TargetProtocol protocol;
  final int timeoutMs;
  final int priority;
  final bool isRequired;

  const NetworkTarget({
    required this.label,
    required this.host,
    required this.port,
    required this.protocol,
    required this.timeoutMs,
    required this.priority,
    required this.isRequired,
  });

  @override
  int get hashCode =>
      label.hashCode ^
      host.hashCode ^
      port.hashCode ^
      protocol.hashCode ^
      timeoutMs.hashCode ^
      priority.hashCode ^
      isRequired.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NetworkTarget &&
          runtimeType == other.runtimeType &&
          label == other.label &&
          host == other.host &&
          port == other.port &&
          protocol == other.protocol &&
          timeoutMs == other.timeoutMs &&
          priority == other.priority &&
          isRequired == other.isRequired;
}

class QualityThresholds {
  final int excellent;
  final int great;
  final int good;
  final int moderate;
  final int poor;

  const QualityThresholds({
    required this.excellent,
    required this.great,
    required this.good,
    required this.moderate,
    required this.poor,
  });

  static Future<QualityThresholds> default_() =>
      RustLib.instance.api.crateApiModelsQualityThresholdsDefault();

  @override
  int get hashCode =>
      excellent.hashCode ^
      great.hashCode ^
      good.hashCode ^
      moderate.hashCode ^
      poor.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QualityThresholds &&
          runtimeType == other.runtimeType &&
          excellent == other.excellent &&
          great == other.great &&
          good == other.good &&
          moderate == other.moderate &&
          poor == other.poor;
}

enum TargetProtocol { tcp, udp }
