// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../models/config.dart';
import '../models/report.dart';
import '../models/target.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Collects multiple latency samples by running checks against all configured targets.
Future<(Uint64List, List<TargetReport>)> collectNetworkSamples(
        {required NetworkConfiguration config}) =>
    RustLib.instance.api
        .crateApiEngineSamplerCollectNetworkSamples(config: config);

/// Analyzes the results of a single sample run across all targets.
Future<BigInt?> analyzeSingleSample(
        {required List<TargetReport> reports,
        required NetworkConfiguration config}) =>
    RustLib.instance.api.crateApiEngineSamplerAnalyzeSingleSample(
        reports: reports, config: config);
