// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: public_member_api_docs, invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `TraceHop`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SecurityFlagsResult>>
abstract class SecurityFlagsResult implements RustOpaqueInterface {
  String get interfaceName;

  bool get isDnsSpoofed;

  bool get isProxyDetected;

  bool get isVpnDetected;

  set interfaceName(String interfaceName);

  set isDnsSpoofed(bool isDnsSpoofed);

  set isProxyDetected(bool isProxyDetected);

  set isVpnDetected(bool isVpnDetected);

  /// Returns a "safe" default state:
  /// - No VPN detected.
  /// - No DNS spoofing detected.
  /// - No proxy detected.
  /// - Interface name set to a generic "unknown".
  static Future<SecurityFlagsResult> default_() =>
      RustLib.instance.api.crateApiModelsNetInfoSecurityFlagsResultDefault();
}

/// The result of a captive portal detection probe.
///
/// Captive portals are commonly found on public WiFi networks (e.g., cafes, airports)
/// where a login or "Terms of Service" acceptance is required before internet access is granted.
class CaptivePortalStatus {
  /// True if the probe was redirected, indicating a captive portal is intercepting traffic.
  final bool isCaptivePortal;

  /// The destination URL of the redirection, if available.
  ///
  /// This is typically the login or landing page of the portal.
  final String? redirectUrl;

  const CaptivePortalStatus({
    required this.isCaptivePortal,
    this.redirectUrl,
  });

  @override
  int get hashCode => isCaptivePortal.hashCode ^ redirectUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CaptivePortalStatus &&
          runtimeType == other.runtimeType &&
          isCaptivePortal == other.isCaptivePortal &&
          redirectUrl == other.redirectUrl;
}

/// Represents the physical or logical medium of the active network connection.
enum ConnectionType {
  /// Connected via a wireless local area network (WiFi).
  wifi,

  /// Connected via mobile data (e.g., 4G LTE, 5G NR).
  cellular,

  /// Connected via a physical Ethernet cable.
  ethernet,

  /// Connected through a Virtual Private Network (VPN) tunnel.
  vpn,

  /// Connected via Bluetooth tethering.
  bluetooth,

  /// A local loopback interface (typically 127.0.0.1).
  loopback,

  /// The connection type could not be identified.
  unknown,
  ;

  /// Returns [ConnectionType::Unknown] as the fallback default.
  static Future<ConnectionType> default_() =>
      RustLib.instance.api.crateApiModelsNetInfoConnectionTypeDefault();
}

/// Internal representation of security-related attributes for the current connection.
class SecurityFlags {
  /// True if the active interface is identified as a VPN or tunnel (e.g., 'tun0', 'utun').
  final bool isVpnDetected;

  /// True if DNS results differ significantly from trusted resolvers, suggesting tampering.
  final bool isDnsSpoofed;

  /// True if a system-level HTTP/HTTPS proxy is detected.
  final bool isProxyDetected;

  /// The system-assigned name of the active network interface (e.g., 'en0', 'wlan0').
  final String interfaceName;

  const SecurityFlags({
    required this.isVpnDetected,
    required this.isDnsSpoofed,
    required this.isProxyDetected,
    required this.interfaceName,
  });

  /// Returns a "safe" default state:
  /// - No VPN detected.
  /// - No DNS spoofing detected.
  /// - No proxy detected.
  /// - Interface name set to a generic "unknown".
  static Future<SecurityFlags> default_() =>
      RustLib.instance.api.crateApiModelsNetInfoSecurityFlagsDefault();

  @override
  int get hashCode =>
      isVpnDetected.hashCode ^
      isDnsSpoofed.hashCode ^
      isProxyDetected.hashCode ^
      interfaceName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SecurityFlags &&
          runtimeType == other.runtimeType &&
          isVpnDetected == other.isVpnDetected &&
          isDnsSpoofed == other.isDnsSpoofed &&
          isProxyDetected == other.isProxyDetected &&
          interfaceName == other.interfaceName;
}
